#!/usr/bin/env python3
"""Behavioural checks for plan.yml's template-owned path guard.

The guard rejects plans whose "Files likely to change" section targets paths
that implement.yml excludes from Codex commits in consumer repos.  Those
exclusions are per-file for ``scripts/`` (driven by the runtime-generated
``scripts/.gitignore`` plus literal ``scripts/...`` entries written to
``FETCHED_MANIFEST``) and blanket for ``prompts/``, ``ai-memory/``,
``.github/prompts/``, and ``.github/scripts/``, so the guard must mirror that
split: a consumer-owned script such as ``scripts/run_validation_repo_checks.sh``
is committable and must be allowed, while runtime-fetched paths such as
``scripts/render_prompt.sh`` are not and must be rejected.
"""

from __future__ import annotations

import os
import re
import shutil
import subprocess
import tempfile
from pathlib import Path

import pytest
import yaml


REPO_ROOT = Path(__file__).resolve().parent.parent
PLAN_WORKFLOW = REPO_ROOT / ".github" / "workflows" / "plan.yml"
IMPLEMENT_WORKFLOW = REPO_ROOT / ".github" / "workflows" / "implement.yml"
GUARD_STEP_NAME = "Guard plans targeting template-owned paths"

# Representative subset of the helpers plan.yml stages into scripts/ and lists
# in the generated scripts/.gitignore.
FETCHED_HELPERS = (
	"gh_helpers.sh",
	"render_prompt.sh",
	"codex_helpers.sh",
	"codex_model_catalog.json",
)


def _guard_body() -> str:
	"""Return the guard step's shell body with GitHub expressions resolved."""
	workflow = yaml.safe_load(PLAN_WORKFLOW.read_text())
	steps = workflow["jobs"]["plan"]["steps"]
	body = next(
		step["run"] for step in steps if step.get("name") == GUARD_STEP_NAME
	)
	body = re.sub(r"\$\{\{\s*github\.repository\s*\}\}", "acme/consumer", body)
	body = re.sub(r"\$\{\{\s*github\.server_url\s*\}\}", "https://github.com", body)
	body = re.sub(r"\$\{\{\s*github\.run_id\s*\}\}", "1", body)
	assert "${{" not in body, "unresolved GitHub expression in guard body"
	return body


def _run_guard(
	plan_text: str,
	gitignore_entries: tuple[str, ...] | None,
	tracked_paths: tuple[str, ...] = (),
):
	"""Execute the guard against a synthetic plan; return (exit_code, output).

	``gitignore_entries`` of ``None`` simulates a bootstrap failure in which
	the support checkout and scripts/.gitignore were never written.
	"""
	env = os.environ.copy()
	env.pop("GIT_DIR", None)
	env.pop("GIT_WORK_TREE", None)
	with tempfile.TemporaryDirectory() as tmp:
		workspace = Path(tmp)
		(workspace / "scripts").mkdir()
		if gitignore_entries is not None:
			(workspace / "scripts" / ".gitignore").write_text(
				"# Auto-generated by coding-workflows — DO NOT EDIT\n"
				+ "\n".join(gitignore_entries)
				+ "\n.gitignore\n"
			)
			implement_workflow = (
				workspace / ".codex-workflow-src" / ".github" / "workflows" / "implement.yml"
			)
			implement_workflow.parent.mkdir(parents=True)
			shutil.copy2(IMPLEMENT_WORKFLOW, implement_workflow)
		if tracked_paths:
			subprocess.run(["git", "init", "-q"], cwd=workspace, env=env, check=True)
			for tracked_path in tracked_paths:
				tracked_file = workspace / tracked_path
				tracked_file.parent.mkdir(parents=True, exist_ok=True)
				tracked_file.write_text("consumer-owned\n")
			subprocess.run(
				["git", "add", "--", *tracked_paths], cwd=workspace, env=env, check=True
			)
		runtime_dir = workspace / "runtime"
		runtime_dir.mkdir()
		codex_output = runtime_dir / "codex_output.txt"
		codex_output.write_text(plan_text)
		env.update(
			{
				"PYTHONDONTWRITEBYTECODE": "1",
				"GITHUB_WORKSPACE": str(workspace),
				"WORKSPACE_PATH": str(workspace),
				"RUNTIME_DIR": str(runtime_dir),
				"CODEX_OUTPUT_FILE": str(codex_output),
				"ISSUE_NUMBER": "1",
				"PLAN_PROGRESS_COMMENT_ID": "",
			}
		)
		proc = subprocess.run(
			["bash", "-c", _guard_body()],
			cwd=str(workspace),
			env=env,
			text=True,
			capture_output=True,
			timeout=60,
		)
		return proc.returncode, proc.stdout + proc.stderr


def _plan_listing(path: str) -> str:
	return f"## Files likely to change\n- `{path}`\n\n## Current behavior\nUnchanged.\n"


@pytest.mark.parametrize(
	"path",
	[
		# The validation entry scripts/validation_template_bootstrap.py seeds
		# into consumer repos. Regression: this used to be rejected, which
		# deadlocked validation fix-up projects (the consumer could never plan
		# a fix for its own validation entry script).
		"scripts/run_validation_repo_checks.sh",
		"scripts/./run_validation_repo_checks.sh",
		"scripts/nested/../run_validation_repo_checks.sh",
		"scripts/subdir/../.github/prompts/mode-plan.txt",
		# implement.yml's own comment cites this as a consumer-owned file the
		# blanket exclusion wrongly blocked.
		"scripts/security/check-npm-audit.js",
		"scripts//security/check-npm-audit.js",
	],
)
def test_consumer_owned_scripts_are_allowed(path: str) -> None:
	returncode, output = _run_guard(_plan_listing(path), FETCHED_HELPERS)
	assert returncode == 0, f"consumer-owned {path} was rejected:\n{output}"


def test_tracked_consumer_serena_template_is_allowed() -> None:
	path = "scripts/templates/serena_project.yml.j2"
	returncode, output = _run_guard(_plan_listing(path), FETCHED_HELPERS, (path,))
	assert returncode == 0, f"consumer-owned {path} was rejected:\n{output}"


@pytest.mark.parametrize(
	"path",
	[
		"scripts.txt",
		"prompts.md",
		"ai-memory.md",
		".github/prompts.md",
		".github/scripts.yml",
	],
)
def test_similarly_prefixed_root_files_are_allowed(path: str) -> None:
	returncode, output = _run_guard(_plan_listing(path), FETCHED_HELPERS)
	assert returncode == 0, f"similarly prefixed {path} was rejected:\n{output}"


def test_other_consumer_github_paths_are_allowed() -> None:
	path = ".github/workflows/custom.yml"
	returncode, output = _run_guard(_plan_listing(path), FETCHED_HELPERS)
	assert returncode == 0, f"consumer-owned {path} was rejected:\n{output}"


@pytest.mark.parametrize(
	"path",
	[
		"scripts/render_prompt.sh",
		"scripts/./render_prompt.sh",
		"scripts//render_prompt.sh",
		"scripts/nested/../render_prompt.sh",
		"scripts/nested/../../.github/prompts/mode-plan.txt",
		"scripts/../../README.md",
		"scripts/gh_helpers.sh",
		# Regression: this implement-only helper is absent from FETCHED_HELPERS,
		# so reading plan.yml's scripts/.gitignore alone would allow it.
		"scripts/codex_stall_guard.sh",
		"scripts/lint_pr_body_auto_close.py",
		# An untracked copy is registered directly in implement.yml's
		# FETCHED_MANIFEST and must remain protected.
		"scripts/templates/serena_project.yml.j2",
		# The catalog is also fetched by the plan job and listed in its gitignore.
		"scripts/codex_model_catalog.json",
		"prompts",
		"prompts/",
		"prompts/mode-plan.txt",
		"prompts//mode-plan.txt",
		"prompts/./mode-plan.txt",
		"prompts/nested/../mode-plan.txt",
		"ai-memory",
		"ai-memory/",
		"ai-memory/schemas/memory_record.v1.json",
		"ai-memory//schemas/memory_record.v1.json",
		"ai-memory/./schemas/memory_record.v1.json",
		"ai-memory/nested/../schemas/memory_record.v1.json",
		".github/prompts",
		".github/prompts/",
		".github/prompts/mode-plan.txt",
		".github//prompts/mode-plan.txt",
		".github/./prompts/mode-plan.txt",
		".github/scripts",
		".github/scripts/",
		".github/scripts/some_helper.sh",
		".github//scripts/some_helper.sh",
		".github/./scripts/some_helper.sh",
		".github/tmp/../scripts/some_helper.sh",
	],
)
def test_template_owned_paths_are_rejected(path: str) -> None:
	returncode, output = _run_guard(_plan_listing(path), FETCHED_HELPERS)
	assert returncode == 1, f"template-owned {path} was allowed:\n{output}"
	assert path in output


@pytest.mark.parametrize("suffix", [".", "!", "?", '"', "'"])
def test_unquoted_template_helper_with_trailing_punctuation_is_rejected(
	suffix: str,
) -> None:
	plan_text = (
		f"## Files likely to change\n- scripts/render_prompt.sh{suffix}\n\n"
		"## Current behavior\nUnchanged.\n"
	)
	returncode, output = _run_guard(plan_text, FETCHED_HELPERS)
	assert returncode == 1, output
	assert "scripts/render_prompt.sh" in output


def test_missing_scripts_gitignore_falls_back_to_blanket_rejection() -> None:
	"""Bootstrap failure must not silently widen what plans may target."""
	returncode, output = _run_guard(
		_plan_listing("scripts/run_validation_repo_checks.sh"), None
	)
	assert returncode == 1
	assert "::warning::Unable to derive fetched-helper manifest" in output
	assert "scripts/.gitignore missing; falling back" in output


@pytest.mark.parametrize("path", ["scripts", "scripts/"])
def test_bare_scripts_directory_reference_is_rejected(path: str) -> None:
	"""A bare scripts directory reference names no file, so stay conservative."""
	returncode, _ = _run_guard(_plan_listing(path), FETCHED_HELPERS)
	assert returncode == 1


def test_prose_mention_outside_files_section_is_allowed() -> None:
	plan_text = (
		"## Files likely to change\n- `README.md`\n\n"
		"## Verification steps\nRun `scripts/render_prompt.sh` to confirm.\n"
	)
	returncode, output = _run_guard(plan_text, FETCHED_HELPERS)
	assert returncode == 0, output


def test_guard_skips_the_canonical_coding_workflows_repository() -> None:
	"""In coding-workflows these paths are the source of truth."""
	workflow = yaml.safe_load(PLAN_WORKFLOW.read_text())
	steps = workflow["jobs"]["plan"]["steps"]
	guard = next(s for s in steps if s.get("name") == GUARD_STEP_NAME)
	assert "endsWith(github.repository, '/coding-workflows')" in guard["if"]
