#!/usr/bin/env python3
"""Contract + functional tests for the deterministic manifest union-merge.

Background
==========

``.ai/.workspace_source_manifest.txt`` is a sorted, unique-line file
inventory generated by ``scripts/workspace_init.sh``. Every AI PR that adds
files appends lines to it, so any two concurrently-open sibling PRs merging
into a shared base conflict on adjacent insertions with near-certainty.
Observed on PR #3909 (2026-08-30): three Codex resolver invocations in one
day, each with the manifest as the ONLY conflicted path, each costing ~5
minutes of LLM time plus a full re-review cycle.

``scripts/review_conflict_prepare.sh`` therefore resolves a two-sided
content conflict on the manifest deterministically — the exact 3-way
resolution of a sorted set-of-lines file is pure set algebra,
``(ours ∩ theirs) ∪ (ours − base) ∪ (theirs − base)`` — and, when the
manifest was the only conflicted path, commits the two-parent merge itself
and sets ``CONFLICT_RESOLVED=true`` so
``scripts/review_conflict_resolve.sh`` short-circuits before any model
invocation.

These tests pin the load-bearing pieces of that contract:

1. The union-merge block exists, is kill-switchable via
   ``CONFLICT_MANIFEST_UNION_ENABLED`` (default true), and excludes
   integration-sync branches (``orchestrator/project-*``), whose
   fingerprint-violation expansion can widen the resolver working set
   after the early-commit decision point.
2. The early-commit branch produces the exact ``[ai-merge-resolve]``
   commit message downstream tooling matches on, signals
   ``CONFLICT_RESOLVED=true``, and does NOT clear ``MERGE_CONFLICT`` —
   the ready-to-merge gate must keep treating the run as a resolver run
   so the resolver commit still gets reviewed before merge.
3. The resolver script's short-circuit sits before any model invocation.
4. Functionally: the live snippet extracted from the prepare script,
   run against a real scratch-repo merge conflict, keeps both sides'
   additions, honours either side's deletions, and emits a sorted,
   deduplicated, LC_ALL=C-collated file.
"""

from __future__ import annotations

import importlib.util
import os
import re
import subprocess
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PREPARE = REPO_ROOT / "scripts" / "review_conflict_prepare.sh"
RESOLVE = REPO_ROOT / "scripts" / "review_conflict_resolve.sh"

MANIFEST_PATH = ".ai/.workspace_source_manifest.txt"
MERGE_RESOLVE_COMMIT_MESSAGE = "[ai-merge-resolve] resolve merge conflicts"


def _prepare_text() -> str:
	return PREPARE.read_text(encoding="utf-8")


def _union_block(text: str) -> str:
	"""The union-merge region: from the path constant to the empty-allowlist check."""
	start = text.index('MANIFEST_UNION_PATH=".ai/.workspace_source_manifest.txt"')
	end = text.index("# When the allowlist is empty there is nothing for Codex to", start)
	return text[start:end]


def _shell_function(text: str, name: str) -> str:
	start = text.index(f"{name}() {{")
	end = text.index("\n}\n", start) + len("\n}")
	return text[start:end]


def test_prepare_names_the_manifest_and_kill_switch() -> None:
	text = _prepare_text()
	assert f'MANIFEST_UNION_PATH="{MANIFEST_PATH}"' in text, (
		"prepare script must pin the manifest path constant"
	)
	block = _union_block(text)
	assert 'CONFLICT_MANIFEST_UNION_ENABLED:-true' in block, (
		"union-merge must be gated on CONFLICT_MANIFEST_UNION_ENABLED with a true default"
	)
	workflow_text = (REPO_ROOT / ".github" / "workflows" / "review_autofix.yml").read_text(
		encoding="utf-8"
	)
	prepare_step = workflow_text.split(
		"- name: Prepare merge-conflict resolver prompt and pre-snapshot", 1
	)[1].split("- name: Run Codex resolver, validate, stage, commit", 1)[0]
	assert "CONFLICT_MANIFEST_UNION_ENABLED: ${{ vars.CONFLICT_MANIFEST_UNION_ENABLED || 'true' }}" in prepare_step, (
		"review_autofix.yml must forward the documented kill switch with a true default"
	)
	assert 'bash "${SUPPORT_SCRIPTS_DIR}/review_conflict_prepare.sh"' in prepare_step


def test_prepare_preserves_separate_resolver_path_classes() -> None:
	text = _prepare_text()
	resolve_text = RESOLVE.read_text(encoding="utf-8")
	initial_snapshot = 'RESOLVER_INITIAL_UNMERGED_PATHS_FILE="${RUNTIME_DIR}/resolver_initial_unmerged_paths.txt"'
	fingerprint_snapshot = 'RESOLVER_FINGERPRINT_ONLY_PATHS_FILE="${RUNTIME_DIR}/resolver_fingerprint_only_paths.txt"'
	assert initial_snapshot in text
	assert fingerprint_snapshot in text
	assert text.index(initial_snapshot) < text.index("# Deterministic union-merge")
	assert 'cp "${_fp_new_tmp}" "${RESOLVER_FINGERPRINT_ONLY_PATHS_FILE}"' in text
	assert initial_snapshot in resolve_text
	assert fingerprint_snapshot in resolve_text
	assert 'wc -l < "${RESOLVER_INITIAL_UNMERGED_PATHS_FILE}"' in resolve_text
	assert 'wc -l < "${RESOLVER_FINGERPRINT_ONLY_PATHS_FILE}"' in resolve_text
	assert "Resolver path classification: initial_unmerged=" in resolve_text


def test_workflows_register_manifest_union_contract_test() -> None:
	expected_invocation = "PYTHONDONTWRITEBYTECODE=1 python3 tests/test_conflict_manifest_union_contract.py"
	for workflow_path in (
		REPO_ROOT / ".github" / "workflows" / "ci.yml",
		REPO_ROOT / ".github" / "workflows" / "mark-stable.yml",
		REPO_ROOT / ".github" / "workflows" / "test-and-mark-stable.yml",
	):
		assert expected_invocation in workflow_path.read_text(encoding="utf-8"), (
			f"{workflow_path} must run the manifest union contract test"
		)


def test_prepare_excludes_integration_sync_branches() -> None:
	block = _union_block(_prepare_text())
	assert "orchestrator/project-*)" in block, (
		"union-merge must exclude orchestrator/project-* integration-sync branches: "
		"their fingerprint-violation expansion widens the resolver working set after "
		"this decision point"
	)
	# The exclusion must precede the set-algebra pipeline within the block.
	assert block.index("orchestrator/project-*)") < block.index("comm -12"), (
		"integration-sync exclusion must come before the union-merge pipeline"
	)


def test_prepare_requires_two_sided_content_conflict() -> None:
	block = _union_block(_prepare_text())
	assert "git ls-files -u --" in block and "*' 2 '*' 3 '*" in block, (
		"union-merge must set-merge only when index stages 2 AND 3 are both present "
		"(two-sided content conflict); delete/modify shapes keep the surviving side"
	)


def test_prepare_delete_modify_arm_placement() -> None:
	block = _union_block(_prepare_text())
	two_sided = block.index("*' 2 '*' 3 '*)")
	delete_modify = block.index("*' 2 '*|*' 3 '*)")
	assert block.index("orchestrator/project-*)") < two_sided < delete_modify, (
		"the delete/modify arm must follow the integration-sync exclusion and the "
		"two-sided set-merge arm"
	)
	assert 'git add -f -- "${MANIFEST_UNION_PATH}"' in block
	assert "leaving it to the Codex resolver." in block, (
		"shapes without stage 2 or 3 must still fall through"
	)


def _scratch_env() -> dict[str, str]:
	return {
		env_name: env_value
		for env_name, env_value in os.environ.items()
		if not env_name.startswith("GIT_") and env_name != "BASH_ENV"
	}


def _git(repo: Path, *args: str, check: bool = True) -> subprocess.CompletedProcess[str]:
	return subprocess.run(
		["git", *args], cwd=repo, env=_scratch_env(), check=check,
		text=True, capture_output=True,
	)


def _delete_modify_fixture(repo: Path, *, ours_deletes: bool, other_conflict: bool, ignore_ai: bool) -> None:
	"""One side deletes the manifest, the other modifies it."""
	_git(repo, "init", "-q", "-b", "main")
	_git(repo, "config", "user.name", "t")
	_git(repo, "config", "user.email", "t@t")
	manifest = repo / MANIFEST_PATH
	manifest.parent.mkdir(parents=True)
	manifest.write_text("a.py\nm.py\nz.py\n", encoding="utf-8")
	(repo / "src").mkdir()
	(repo / "src" / "app.py").write_text("base\n", encoding="utf-8")
	if ignore_ai:
		(repo / ".gitignore").write_text(".ai/\n", encoding="utf-8")
	_git(repo, "add", "-f", "-A")
	_git(repo, "commit", "-qm", "base")
	_git(repo, "checkout", "-q", "-b", "deleter")
	_git(repo, "rm", "-q", "--", MANIFEST_PATH)
	if other_conflict:
		(repo / "src" / "app.py").write_text("deleter\n", encoding="utf-8")
		_git(repo, "add", "--", "src/app.py")
	_git(repo, "commit", "-qm", "delete manifest")
	_git(repo, "checkout", "-q", "main")
	_git(repo, "checkout", "-q", "-b", "modifier")
	manifest.write_text("z.py\nm.py\n\nb.py\na.py\na.py\n", encoding="utf-8")
	if other_conflict:
		(repo / "src" / "app.py").write_text("modifier\n", encoding="utf-8")
	_git(repo, "add", "-f", "-A")
	_git(repo, "commit", "-qm", "modify manifest")
	ours, theirs = ("deleter", "modifier") if ours_deletes else ("modifier", "deleter")
	_git(repo, "checkout", "-q", ours)
	merge = _git(repo, "merge", "--no-commit", "--no-ff", theirs, check=False)
	assert merge.returncode != 0, "fixture must produce a conflict"


def _run_union_block(repo: Path, tmp: Path, block: str, **env_overrides: str) -> tuple[subprocess.CompletedProcess[str], Path, Path]:
	allowlist = tmp / "allowlist.txt"
	github_env = tmp / "github.env"
	github_env.write_text("", encoding="utf-8")
	stash = tmp / "stash"
	stash.mkdir(exist_ok=True)
	allowlist.write_text(
		_git(repo, "diff", "--name-only", "--diff-filter=U").stdout, encoding="utf-8"
	)
	script = f"""set -euo pipefail
RESOLVER_ALLOWLIST_FILE={allowlist!s}
GITHUB_ENV={github_env!s}
RESOLVE_STASH={stash!s}
_merge_stderr_file={tmp / "merge_stderr.txt"!s}
_resolver_allowlist_count="$(wc -l < "${{RESOLVER_ALLOWLIST_FILE}}" | tr -d '[:space:]')"
{block}
"""
	env = _scratch_env()
	env.update({"TARGET_BRANCH": "ai/issue-1", "IS_WORKFLOW_SOURCE_REPO": "true"})
	env.update(env_overrides)
	result = subprocess.run(["bash", "-c", script], cwd=repo, env=env, text=True, capture_output=True)
	return result, allowlist, github_env


def _check_delete_modify_with_other_conflict(block: str) -> None:
	with tempfile.TemporaryDirectory() as raw_tmp:
		tmp = Path(raw_tmp)
		repo = tmp / "repo"
		repo.mkdir()
		_delete_modify_fixture(repo, ours_deletes=True, other_conflict=True, ignore_ai=False)
		result, allowlist, github_env = _run_union_block(repo, tmp, block)
		assert result.returncode == 0, result.stderr
		assert _git(repo, "ls-files", "-u", "--", MANIFEST_PATH).stdout == "", (
			"delete/modify manifest conflict must be resolved before the model resolver"
		)
		assert allowlist.read_text(encoding="utf-8").splitlines() == ["src/app.py"], (
			"only the non-manifest conflict may reach the resolver; no .ai path is admitted"
		)
		assert (repo / MANIFEST_PATH).read_text(encoding="utf-8") == "a.py\nb.py\nm.py\nz.py\n"
		assert "CONFLICT_RESOLVED=true" not in github_env.read_text(encoding="utf-8")
		assert "delete/modify (kept stage 3)" in result.stdout


def test_manifest_delete_modify_resolved_with_other_conflict() -> None:
	"""Regression for #6575: the shape that reached the sandbox and failed closed."""
	_check_delete_modify_with_other_conflict(_union_block(_prepare_text()))


def test_manifest_modify_delete_stage2_only() -> None:
	with tempfile.TemporaryDirectory() as raw_tmp:
		tmp = Path(raw_tmp)
		repo = tmp / "repo"
		repo.mkdir()
		_delete_modify_fixture(repo, ours_deletes=False, other_conflict=False, ignore_ai=True)
		result, _allowlist, github_env = _run_union_block(repo, tmp, _union_block(_prepare_text()))
		assert result.returncode == 0, result.stderr
		assert "delete/modify (kept stage 2)" in result.stdout
		parents = _git(repo, "rev-list", "--parents", "-n", "1", "HEAD").stdout.split()
		assert len(parents) == 3, "manifest-only resolution must be a two-parent merge commit"
		assert _git(repo, "log", "-1", "--format=%s").stdout.strip() == MERGE_RESOLVE_COMMIT_MESSAGE
		env_text = github_env.read_text(encoding="utf-8")
		assert "CONFLICT_RESOLVED=true" in env_text
		assert "MERGE_CONFLICT=false" not in env_text
		assert _git(repo, "show", f"HEAD:{MANIFEST_PATH}").stdout == "a.py\nb.py\nm.py\nz.py\n"


def test_manifest_delete_modify_respects_kill_switch() -> None:
	with tempfile.TemporaryDirectory() as raw_tmp:
		tmp = Path(raw_tmp)
		repo = tmp / "repo"
		repo.mkdir()
		_delete_modify_fixture(repo, ours_deletes=True, other_conflict=True, ignore_ai=False)
		result, allowlist, _github_env = _run_union_block(
			repo, tmp, _union_block(_prepare_text()), CONFLICT_MANIFEST_UNION_ENABLED="false"
		)
		assert result.returncode == 0, result.stderr
		assert _git(repo, "ls-files", "-u", "--", MANIFEST_PATH).stdout != ""
		assert MANIFEST_PATH in allowlist.read_text(encoding="utf-8").splitlines()


def _workspace_module():
	spec = importlib.util.spec_from_file_location(
		"review_untrusted_workspace_under_test", REPO_ROOT / "scripts" / "review_untrusted_workspace.py"
	)
	module = importlib.util.module_from_spec(spec)
	assert spec.loader is not None
	spec.loader.exec_module(module)
	return module


def test_rejection_rule_mirrors_allowed_and_keeps_ai_excluded() -> None:
	workspace = _workspace_module()
	assert workspace.allowed(".ai/other.txt") is False
	assert workspace.rejection_rule(".ai/other.txt") == "excluded_dir"
	assert workspace.allowed(MANIFEST_PATH) is False
	for name in (
		"README.md", "scripts/a.sh", ".ai/x.txt", "../x", "a\nb.py", ".env.local",
		"foo.pem", ".hidden/x.py", ".github/workflows/ci.yml", "bin/tool",
		"tests/test_audit_plans_command.py",
	):
		assert workspace.allowed(name) == (workspace.rejection_rule(name) is None), name


def test_sanitize_log_path_bounds_untrusted_names() -> None:
	workspace = _workspace_module()
	cleaned = workspace.sanitize_log_path("a\n::error::x")
	assert "\n" not in cleaned and cleaned == "a?::error::x"
	long_name = workspace.sanitize_log_path("x" * 500)
	assert len(long_name) == 200 and long_name.endswith("...")


def test_report_rejections_names_refused_path_without_contents() -> None:
	with tempfile.TemporaryDirectory() as raw_tmp:
		tmp = Path(raw_tmp)
		host = tmp / "host"
		(host / ".ai").mkdir(parents=True)
		(host / "src").mkdir()
		(host / ".ai" / "other.txt").write_text("SECRET-CONTENT\n", encoding="utf-8")
		(host / "src" / "ok.py").write_text("print(1)\n", encoding="utf-8")
		paths = tmp / "paths.txt"
		paths.write_text(".ai/other.txt\nsrc/ok.py\n", encoding="utf-8")
		result = subprocess.run(
			["python3", str(REPO_ROOT / "scripts" / "review_untrusted_workspace.py"),
			 "report-rejections", str(host), str(paths)],
			env={**_scratch_env(), "PYTHONDONTWRITEBYTECODE": "1"}, text=True, capture_output=True,
		)
		assert result.returncode == 3, result.stderr
		lines = [line for line in result.stderr.splitlines() if line.startswith("REVIEW_UNTRUSTED_PATH_REJECTED")]
		assert lines == ["REVIEW_UNTRUSTED_PATH_REJECTED path=.ai/other.txt rule=excluded_dir"]
		assert "SECRET-CONTENT" not in result.stderr + result.stdout
		many = tmp / "many.txt"
		many.write_text("".join(f".ai/f{i}.txt\n" for i in range(12)), encoding="utf-8")
		capped = subprocess.run(
			["python3", str(REPO_ROOT / "scripts" / "review_untrusted_workspace.py"),
			 "report-rejections", str(host), str(many)],
			env={**_scratch_env(), "PYTHONDONTWRITEBYTECODE": "1"}, text=True, capture_output=True,
		)
		assert capped.returncode == 3
		capped_lines = capped.stderr.splitlines()
		assert len([line for line in capped_lines if line.startswith("REVIEW_UNTRUSTED_PATH_REJECTED path=")]) == 10
		assert "REVIEW_UNTRUSTED_PATH_REJECTED_TRUNCATED omitted=2" in capped_lines


def test_prepare_early_commit_branch_contract() -> None:
	block = _union_block(_prepare_text())
	commit_index = block.index(f'git commit -m "{MERGE_RESOLVE_COMMIT_MESSAGE}"')
	for hygiene_command in (
		"git rm -r --cached --ignore-unmatch -- node_modules",
		"git reset -q HEAD -- 'prompts' '.github/scripts' '.github/prompts' 'ai-memory'",
	):
		assert block.index(hygiene_command) < commit_index, (
			f"consumer-repo hygiene must run before the manifest-only commit: {hygiene_command}"
		)
	assert f'git commit -m "{MERGE_RESOLVE_COMMIT_MESSAGE}"' in block, (
		"manifest-only resolutions must commit with the exact [ai-merge-resolve] "
		"message downstream tooling matches on"
	)
	assert 'echo "CONFLICT_RESOLVED=true" >> "$GITHUB_ENV"' in block, (
		"manifest-only resolutions must signal CONFLICT_RESOLVED=true so push, "
		"Telegram, and the legacy re-dispatch fire as in the Codex path"
	)
	assert "MERGE_CONFLICT=false" not in block, (
		"the union-merge block must NOT clear MERGE_CONFLICT: the ready-to-merge "
		"gate keys off it to keep resolver commits reviewed before merge"
	)


def test_prepare_uses_c_locale_set_algebra() -> None:
	block = _union_block(_prepare_text())
	for needle in (
		'LC_ALL=C comm -12 "${_mu_dir}/ours" "${_mu_dir}/theirs"',
		'LC_ALL=C comm -13 "${_mu_dir}/base" "${_mu_dir}/ours"',
		'LC_ALL=C comm -13 "${_mu_dir}/base" "${_mu_dir}/theirs"',
	):
		assert needle in block, f"set-algebra line missing or reflowed: {needle}"
	assert "LC_ALL=C sort -u" in block, (
		"stage inputs and the merged output must be LC_ALL=C sorted to match "
		"materialize_source_tree()'s Python str sort"
	)


def test_resolve_short_circuits_before_model_invocation() -> None:
	text = RESOLVE.read_text(encoding="utf-8")
	guard = re.search(
		r'if \[ "\$\{CONFLICT_RESOLVED:-false\}" = "true" \]; then\n[^\n]*\n\s*exit 0',
		text,
	)
	assert guard is not None, (
		"review_conflict_resolve.sh must exit 0 when CONFLICT_RESOLVED=true was "
		"already set by the prepare step"
	)
	first_model_ref = min(
		i for i in (text.find("opencode_helpers.sh"), text.find("OPENCODE_HELPERS_PATH")) if i >= 0
	)
	assert guard.start() < first_model_ref, (
		"the CONFLICT_RESOLVED short-circuit must precede every model-invocation "
		"code path in review_conflict_resolve.sh"
	)


def test_resolver_index_guard_precedes_no_change_and_commit_paths() -> None:
	text = RESOLVE.read_text(encoding="utf-8")
	guard_call = text.index("if ! verify_resolver_index_complete_or_fail; then")
	assert guard_call < text.index('echo "No staged merge resolution changes remain', guard_call)
	assert guard_call < text.index(f'git commit -m "{MERGE_RESOLVE_COMMIT_MESSAGE}"', guard_call)


def test_resolver_staging_failure_is_path_specific_and_fatal() -> None:
	text = RESOLVE.read_text(encoding="utf-8")
	function_text = _shell_function(text, "stage_resolver_touched_path_or_fail")
	with tempfile.TemporaryDirectory() as tmp:
		repo = Path(tmp) / "repo"
		repo.mkdir()
		github_env = Path(tmp) / "github.env"
		scratch_git_env = {
			env_name: env_value
			for env_name, env_value in os.environ.items()
			if not env_name.startswith("GIT_") and env_name != "BASH_ENV"
		}
		subprocess.run(["git", "init", "-q", "-b", "main"], cwd=repo, env=scratch_git_env, check=True)
		(repo / "tracked.txt").write_text("content\n", encoding="utf-8")
		script = f"""set -euo pipefail
GITHUB_ENV={github_env!s}
{function_text}
git() {{
	if [ "$1" = "add" ]; then
		return 42
	fi
	command git "$@"
}}
if stage_resolver_touched_path_or_fail tracked.txt; then
	exit 91
fi
"""
		result = subprocess.run(
			["bash", "-c", script], cwd=repo, env=scratch_git_env,
			text=True, capture_output=True,
		)
		assert result.returncode == 0, result.stderr
		assert "Failed to stage conflict resolver path: tracked.txt" in result.stdout
		assert "git exit=42" in result.stdout
		assert github_env.read_text(encoding="utf-8") == "CONFLICT_RESOLVED=false\n"


def test_marker_free_unmerged_index_entry_blocks_commit() -> None:
	text = RESOLVE.read_text(encoding="utf-8")
	function_text = _shell_function(text, "verify_resolver_index_complete_or_fail")
	with tempfile.TemporaryDirectory() as tmp:
		repo = Path(tmp) / "repo"
		repo.mkdir()
		runtime_dir = Path(tmp) / "runtime"
		runtime_dir.mkdir()
		github_env = Path(tmp) / "github.env"
		scratch_git_env = {
			env_name: env_value
			for env_name, env_value in os.environ.items()
			if not env_name.startswith("GIT_") and env_name != "BASH_ENV"
		}

		def git(*args: str, check: bool = True) -> subprocess.CompletedProcess[str]:
			return subprocess.run(
				["git", *args], cwd=repo, env=scratch_git_env, check=check,
				text=True, capture_output=True,
			)

		git("init", "-q", "-b", "main")
		git("config", "user.name", "t")
		git("config", "user.email", "t@t")
		conflicted = repo / "marker-free.txt"
		conflicted.write_text("base\n", encoding="utf-8")
		git("add", "--", "marker-free.txt")
		git("commit", "-qm", "base")
		git("checkout", "-q", "-b", "modified")
		conflicted.write_text("modified without conflict markers\n", encoding="utf-8")
		git("commit", "-am", "modify", "-q")
		git("checkout", "-q", "main")
		git("rm", "-q", "--", "marker-free.txt")
		git("commit", "-qm", "delete")
		before_head = git("rev-parse", "HEAD").stdout.strip()
		merge = git("merge", "--no-commit", "--no-ff", "modified", check=False)
		assert merge.returncode != 0
		assert "<<<<<<<" not in conflicted.read_text(encoding="utf-8")

		script = f"""set -euo pipefail
RUNTIME_DIR={runtime_dir!s}
GITHUB_ENV={github_env!s}
{function_text}
if verify_resolver_index_complete_or_fail; then
	exit 91
fi
"""
		result = subprocess.run(
			["bash", "-c", script], cwd=repo, env=scratch_git_env,
			text=True, capture_output=True,
		)
		assert result.returncode == 0, result.stderr
		assert "Conflict resolver left unmerged Git index entries" in result.stdout
		assert "marker-free.txt" in result.stdout
		assert github_env.read_text(encoding="utf-8") == "CONFLICT_RESOLVED=false\n"
		assert git("rev-parse", "HEAD").stdout.strip() == before_head
		assert git("diff", "--name-only", "--diff-filter=U", "--").stdout.strip() == "marker-free.txt"


def test_union_merge_pipeline_functional() -> None:
	"""Run the live snippet from the prepare script against a real conflict.

	The snippet between the mktemp line and its cleanup only references
	``MANIFEST_UNION_PATH`` and ``_mu_dir``, so it is runnable verbatim
	inside a scratch repository with an in-progress conflicted merge.
	Testing the extracted live text (not a copy) keeps this green only
	while the shipped pipeline itself is correct.
	"""
	text = _prepare_text()
	block = _union_block(text)
	start = block.index('_mu_dir="$(mktemp -d)"')
	end = block.index('rm -rf "${_mu_dir}"', start) + len('rm -rf "${_mu_dir}"')
	snippet = "\n".join(line.strip() for line in block[start:end].splitlines())

	with tempfile.TemporaryDirectory() as tmp:
		repo = Path(tmp) / "repo"
		repo.mkdir()
		scratch_git_env = {
			env_name: env_value
			for env_name, env_value in os.environ.items()
			if not env_name.startswith("GIT_") and env_name != "BASH_ENV"
		}

		def git(*args: str) -> None:
			subprocess.run(
				["git", *args], cwd=repo, check=True,
				env=scratch_git_env,
				stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
			)

		manifest = repo / MANIFEST_PATH
		git("init", "-q", "-b", "main")
		git("config", "user.name", "t")
		git("config", "user.email", "t@t")
		manifest.parent.mkdir(parents=True)
		manifest.write_text("a.py\nb.py\nm.py\nz.py\n", encoding="utf-8")
		git("add", "-A")
		git("commit", "-qm", "base")
		git("checkout", "-q", "-b", "ours")
		manifest.write_text("a.py\nb.py\nc.py\nm.py\nz.py\n", encoding="utf-8")
		git("commit", "-aqm", "ours adds c.py")
		git("checkout", "-q", "main")
		git("checkout", "-q", "-b", "theirs")
		manifest.write_text("a.py\nb.py\nd.py\nz.py\n", encoding="utf-8")
		git("commit", "-aqm", "theirs adds d.py, removes m.py")
		git("checkout", "-q", "ours")
		merge = subprocess.run(
			["git", "merge", "--no-commit", "--no-ff", "theirs"],
			cwd=repo, env=scratch_git_env,
			stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
		)
		assert merge.returncode != 0, "fixture must produce a manifest conflict"

		script = f'set -euo pipefail\nMANIFEST_UNION_PATH="{MANIFEST_PATH}"\n{snippet}\n'
		subprocess.run(["bash", "-c", script], cwd=repo, env=scratch_git_env, check=True)

		got = manifest.read_text(encoding="utf-8")
		assert got == "a.py\nb.py\nc.py\nd.py\nz.py\n", (
			f"union-merge must keep both sides' additions and honour theirs-side "
			f"deletion of m.py; got: {got!r}"
		)


def main() -> int:
	test_funcs = [v for k, v in sorted(globals().items()) if k.startswith("test_")]
	passed = 0
	failed = 0
	for func in test_funcs:
		name = func.__name__
		try:
			func()
			print(f"  PASS  {name}")
			passed += 1
		except Exception as e:
			print(f"  FAIL  {name}: {e}")
			failed += 1
	print(f"\n{passed} passed, {failed} failed, {passed + failed} total")
	return 1 if failed > 0 else 0


if __name__ == "__main__":
	raise SystemExit(main())
