"""Contract for `.claude/scripts/security_pass_skip.py`, the check that lets an
issue-mode project skip its own security pass only for issues the issue
automation created and labelled (security finding
`mutable-label-skips-security-pass`, issue #4623)."""

from __future__ import annotations

import importlib.util
import json
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
SCRIPTS = ROOT / ".claude" / "scripts"
TEMPLATE_SCRIPTS = ROOT / "workflow-templates" / ".claude" / "scripts"


def _load():
	spec = importlib.util.spec_from_file_location("security_pass_skip", SCRIPTS / "security_pass_skip.py")
	module = importlib.util.module_from_spec(spec)
	spec.loader.exec_module(module)
	return module


skip = _load()

REPO = "o/r"
OWNER = "owner-login"
CREATED = "2026-09-27T08:25:06Z"
MARKERS = {
	"ai:security": "<!-- ai:security-finding:mutable-label -->\nRefs #3576\n",
	"ai:check-triage": "<!-- check-failure-triage:fp=abc123 -->\n<!-- check-failure-triage:gen=1 -->\n",
	"ai:workflow-heal": "<!-- workflow-failure-heal:fp=def456 -->\n<!-- workflow-failure-heal:gen=1 -->\n",
}


def _issue(label="ai:security", login=OWNER, user_type="User", association="OWNER", body=None, labels=None, **extra):
	issue = {
		"number": 4623,
		"user": {"login": login, "type": user_type},
		"author_association": association,
		"created_at": CREATED,
		"labels": [{"name": name} for name in (labels if labels is not None else [label, "ai:claude"])],
		"body": MARKERS[label] + "\nGenerated by automation.\n" if body is None else body,
	}
	issue.update(extra)
	return issue


def _labeled(label, actor=OWNER, at="2026-09-27T08:25:07Z"):
	return {"event": "labeled", "actor": {"login": actor}, "created_at": at, "label": {"name": label}}


def _tracker(login=OWNER, labels=("ai:security-audit",), body="<!-- ai:security-audit-tracker:v1 -->\n# AI Security Audit Tracker\n"):
	return {"number": 3576, "user": {"login": login, "type": "User"}, "labels": [{"name": name} for name in labels], "body": body}


def _decide(issue, events, tracker=None, calls=None):
	def fetch_tracker(number):
		if calls is not None:
			calls.append(number)
		return tracker

	return skip.decide_security_pass_skip(issue, events, fetch_tracker)


@pytest.mark.parametrize("label", list(MARKERS))
def test_automation_issue_skips(label):
	result = _decide(_issue(label), [_labeled(label)], _tracker())
	assert result == {"skip": True, "label": label, "reason": f"{label}: created and labelled by the issue automation"}


def test_github_actions_bot_is_automation():
	issue = _issue("ai:check-triage", login="github-actions[bot]", user_type="Bot", association="NONE")
	result = _decide(issue, [_labeled("ai:check-triage", actor="github-actions[bot]")])
	assert result["skip"] is True


def test_no_skip_label_runs():
	result = _decide(_issue(labels=["bug"]), [])
	assert result == {"skip": False, "label": None, "reason": "no skip label"}


@pytest.mark.parametrize("association", ["COLLABORATOR", "MEMBER", "CONTRIBUTOR", "NONE"])
def test_collaborator_labelled_issue_runs(association):
	# The finding: a collaborator opens an ordinary issue and labels it ai:security.
	issue = _issue(login="collab", association=association)
	result = _decide(issue, [_labeled("ai:security", actor="collab")], _tracker(login="collab"))
	assert result["skip"] is False and "is not the issue automation" in result["reason"]


def test_user_impersonating_the_bot_login_runs():
	issue = _issue(login="github-actions[bot]", user_type="User", association="NONE")
	assert _decide(issue, [_labeled("ai:security", actor="github-actions[bot]")], _tracker())["skip"] is False


def test_other_bot_runs():
	issue = _issue(login="renovate[bot]", user_type="Bot", association="NONE")
	assert _decide(issue, [_labeled("ai:security", actor="renovate[bot]")], _tracker())["skip"] is False


def test_label_added_later_by_someone_else_runs():
	# An owner's ordinary issue that a triage-role user labelled afterwards.
	result = _decide(_issue(), [_labeled("ai:security", actor="triager", at="2026-09-28T00:00:00Z")], _tracker())
	assert result["skip"] is False and "applied by triager" in result["reason"]


def test_label_reapplied_by_someone_else_runs():
	events = [
		_labeled("ai:security"),
		{"event": "unlabeled", "actor": {"login": "triager"}, "created_at": "2026-09-27T09:00:00Z", "label": {"name": "ai:security"}},
		_labeled("ai:security", actor="triager", at="2026-09-27T09:01:00Z"),
	]
	assert _decide(_issue(), events, _tracker())["skip"] is False


def test_label_added_by_author_after_creation_runs():
	result = _decide(_issue(), [_labeled("ai:security", at="2026-09-27T08:27:07Z")], _tracker())
	assert result["skip"] is False and "not at creation" in result["reason"]


def test_label_event_dated_before_creation_runs():
	result = _decide(_issue(), [_labeled("ai:security", at="2026-09-27T08:25:01Z")], _tracker())
	assert result["skip"] is False
	assert "5s before the issue's creation" in result["reason"] and "-5s" not in result["reason"]


def test_label_within_window_skips():
	assert _decide(_issue(), [_labeled("ai:security", at="2026-09-27T08:27:06Z")], _tracker())["skip"] is True


def test_earliest_label_event_is_used_whatever_the_order():
	# Newest-first order: a later same-author re-application must not hide the
	# creation-time event.
	events = [
		_labeled("ai:security", at="2026-09-28T00:00:00Z"),
		{"event": "unlabeled", "actor": {"login": OWNER}, "created_at": "2026-09-27T09:00:00Z", "label": {"name": "ai:security"}},
		_labeled("ai:security"),
	]
	assert _decide(_issue(), events, _tracker())["skip"] is True


def test_unreadable_label_event_time_runs():
	events = [_labeled("ai:security"), _labeled("ai:security", at="not-a-time")]
	result = _decide(_issue(), events, _tracker())
	assert result["skip"] is False and "no readable created_at" in result["reason"]


def test_missing_labeled_event_runs():
	result = _decide(_issue(), [_labeled("ai:claude")], _tracker())
	assert result["skip"] is False and "no labeled event for ai:security" in result["reason"]


def test_unreadable_events_run():
	assert _decide(_issue(), None, _tracker())["reason"] == "issue events could not be read"


def test_full_event_page_is_not_verifiable():
	events = [_labeled("ai:security")] + [_labeled("x") for _ in range(skip.EVENTS_PAGE_SIZE - 1)]
	result = _decide(_issue(), events, _tracker())
	assert result["skip"] is False and "not verifiable" in result["reason"]


@pytest.mark.parametrize("label", list(MARKERS))
def test_missing_marker_runs(label):
	result = _decide(_issue(label, body="Refs #3576\nno marker here\n"), [_labeled(label)], _tracker())
	assert result["skip"] is False and f"body has no {label} automation marker" in result["reason"]


def test_marker_of_another_label_runs():
	result = _decide(_issue("ai:security", body=MARKERS["ai:workflow-heal"] + "Refs #3576\n"), [_labeled("ai:security")], _tracker())
	assert result["skip"] is False


def test_marker_must_start_a_line():
	body = "quoted: <!-- ai:security-finding:x -->\nRefs #3576\n"
	assert _decide(_issue(body=body), [_labeled("ai:security")], _tracker())["skip"] is False


def test_security_without_tracker_ref_runs():
	calls: list[int] = []
	result = _decide(_issue(body="<!-- ai:security-finding:x -->\n"), [_labeled("ai:security")], _tracker(), calls)
	assert result["skip"] is False and "no Refs #<tracker> line" in result["reason"] and calls == []


@pytest.mark.parametrize(
	("tracker", "reason"),
	[
		(None, "could not be read"),
		(_tracker(labels=("bug",)), "is not labelled ai:security-audit"),
		(_tracker(body="# fake tracker\n"), "has no audit tracker marker"),
		(_tracker(login="collab"), "was not created by the follow-up's author"),
		({**_tracker(), "pull_request": {}}, "is a pull request"),
	],
)
def test_invalid_tracker_runs(tracker, reason):
	result = _decide(_issue(), [_labeled("ai:security")], tracker)
	assert result["skip"] is False and reason in result["reason"]


def test_tracker_is_only_read_for_security():
	calls: list[int] = []
	_decide(_issue("ai:workflow-heal"), [_labeled("ai:workflow-heal")], None, calls)
	assert calls == []


def test_second_label_can_verify_when_first_does_not():
	issue = _issue("ai:workflow-heal", labels=["ai:security", "ai:workflow-heal"])
	events = [_labeled("ai:security", actor="triager", at="2026-09-28T00:00:00Z"), _labeled("ai:workflow-heal")]
	result = _decide(issue, events)
	assert result["skip"] is True and result["label"] == "ai:workflow-heal"


def test_every_failed_label_is_reported():
	issue = _issue("ai:check-triage", labels=["ai:check-triage", "ai:workflow-heal"])
	result = _decide(issue, [_labeled("ai:check-triage", actor="triager")])
	assert result["skip"] is False
	assert result["reason"].startswith("ai:check-triage: ai:check-triage was applied by triager")
	assert "; ai:workflow-heal: no labeled event for ai:workflow-heal" in result["reason"]


def test_pull_request_is_not_an_issue():
	assert _decide(_issue(pull_request={}), [_labeled("ai:security")], _tracker())["reason"] == "not an issue"


def _stub_gh(monkeypatch, responses):
	calls: list[str] = []

	def fake(path):
		calls.append(path)
		value = responses[path]
		if isinstance(value, Exception):
			raise value
		return value

	monkeypatch.setattr(skip, "_gh_get_json", fake)
	return calls


def test_cli_skip(monkeypatch, capsys):
	calls = _stub_gh(monkeypatch, {
		"repos/o/r/issues/4623": _issue(),
		"repos/o/r/issues/4623/events?per_page=100": [_labeled("ai:security")],
		"repos/o/r/issues/3576": _tracker(),
	})
	assert skip.main(["--repo", REPO, "--issue", "4623"]) == 0
	assert json.loads(capsys.readouterr().out)["skip"] is True
	assert len(calls) == 3


def test_cli_no_skip_label_costs_one_call(monkeypatch, capsys):
	calls = _stub_gh(monkeypatch, {"repos/o/r/issues/4623": _issue(labels=["bug"])})
	assert skip.main(["--repo", REPO, "--issue", "4623"]) == 0
	assert json.loads(capsys.readouterr().out) == {"skip": False, "label": None, "reason": "no skip label"}
	assert calls == ["repos/o/r/issues/4623"]


def test_cli_non_automation_author_costs_one_call(monkeypatch, capsys):
	calls = _stub_gh(monkeypatch, {"repos/o/r/issues/4623": _issue(login="collab", association="COLLABORATOR")})
	assert skip.main(["--repo", REPO, "--issue", "4623"]) == 0
	assert json.loads(capsys.readouterr().out)["skip"] is False
	assert calls == ["repos/o/r/issues/4623"]


def test_cli_tracker_read_failure_runs(monkeypatch, capsys):
	_stub_gh(monkeypatch, {
		"repos/o/r/issues/4623": _issue(),
		"repos/o/r/issues/4623/events?per_page=100": [_labeled("ai:security")],
		"repos/o/r/issues/3576": skip.ReadError("HTTP 502"),
	})
	assert skip.main(["--repo", REPO, "--issue", "4623"]) == 0
	out = json.loads(capsys.readouterr().out)
	assert out["skip"] is False and "could not be read" in out["reason"]


def test_cli_issue_read_failure_exits_2(monkeypatch, capsys):
	_stub_gh(monkeypatch, {"repos/o/r/issues/4623": skip.ReadError("HTTP 404")})
	assert skip.main(["--repo", REPO, "--issue", "4623"]) == 2
	out = json.loads(capsys.readouterr().out)
	assert out["skip"] is False and "HTTP 404" in out["error"]


def test_cli_events_read_failure_exits_2(monkeypatch, capsys):
	_stub_gh(monkeypatch, {
		"repos/o/r/issues/4623": _issue(),
		"repos/o/r/issues/4623/events?per_page=100": skip.ReadError("HTTP 502"),
	})
	assert skip.main(["--repo", REPO, "--issue", "4623"]) == 2
	assert json.loads(capsys.readouterr().out)["skip"] is False


def test_gh_error_detail_falls_back_to_stdout_when_stderr_is_blank(monkeypatch):
	class Proc:
		returncode = 1
		stderr = "  \n"
		stdout = '{"message": "Not Found"}\ngh: Not Found (HTTP 404)\n'

	monkeypatch.setattr(skip.subprocess, "run", lambda *args, **kwargs: Proc())
	with pytest.raises(skip.ReadError, match=r"HTTP 404"):
		skip._gh_get_json("repos/o/r/issues/1")


@pytest.mark.parametrize("argv", [["--repo", "bad", "--issue", "1"], ["--repo", REPO, "--issue", "0"]])
def test_cli_bad_arguments_exit_1(argv, capsys):
	assert skip.main(argv) == 1
	assert json.loads(capsys.readouterr().out)["skip"] is False


def test_skip_labels_match_the_router():
	import sys

	sys.path.insert(0, str(ROOT / "scripts"))
	import claude_issue_route as route

	assert tuple(skip.SKIP_LABEL_MARKERS) == route.SECURITY_PASS_SKIP_LABELS


def test_template_copy_matches():
	assert (SCRIPTS / "security_pass_skip.py").read_bytes() == (TEMPLATE_SCRIPTS / "security_pass_skip.py").read_bytes()


def test_settings_allow_the_script():
	for settings in (ROOT / ".claude" / "settings.json", ROOT / "workflow-templates" / ".claude" / "settings.json"):
		allow = json.loads(settings.read_text(encoding="utf-8"))["permissions"]["allow"]
		assert "Bash(python3 .claude/scripts/security_pass_skip.py *)" in allow, settings
		assert "Bash(PYTHONDONTWRITEBYTECODE=1 python3 .claude/scripts/security_pass_skip.py *)" in allow, settings
