#!/usr/bin/env python3
"""Contract + functional tests for the deterministic manifest union-merge.

Background
==========

``.ai/.workspace_source_manifest.txt`` is a sorted, unique-line file
inventory generated by ``scripts/workspace_init.sh``. Every AI PR that adds
files appends lines to it, so any two concurrently-open sibling PRs merging
into a shared base conflict on adjacent insertions with near-certainty.
Observed on PR #3909 (2026-08-30): three Codex resolver invocations in one
day, each with the manifest as the ONLY conflicted path, each costing ~5
minutes of LLM time plus a full re-review cycle.

``scripts/review_conflict_prepare.sh`` therefore resolves a two-sided
content conflict on the manifest deterministically — the exact 3-way
resolution of a sorted set-of-lines file is pure set algebra,
``(ours ∩ theirs) ∪ (ours − base) ∪ (theirs − base)`` — and, when the
manifest was the only conflicted path, commits the two-parent merge itself
and sets ``CONFLICT_RESOLVED=true`` so
``scripts/review_conflict_resolve.sh`` short-circuits before any model
invocation.

These tests pin the load-bearing pieces of that contract:

1. The union-merge block exists, is kill-switchable via
   ``CONFLICT_MANIFEST_UNION_ENABLED`` (default true), and excludes
   integration-sync branches (``orchestrator/project-*``), whose
   fingerprint-violation expansion can widen the resolver working set
   after the early-commit decision point.
2. The early-commit branch produces the exact ``[ai-merge-resolve]``
   commit message downstream tooling matches on, signals
   ``CONFLICT_RESOLVED=true``, and does NOT clear ``MERGE_CONFLICT`` —
   the ready-to-merge gate must keep treating the run as a resolver run
   so the resolver commit still gets reviewed before merge.
3. The resolver script's short-circuit sits before any model invocation.
4. Functionally: the live snippet extracted from the prepare script,
   run against a real scratch-repo merge conflict, keeps both sides'
   additions, honours either side's deletions, and emits a sorted,
   deduplicated, LC_ALL=C-collated file.
"""

from __future__ import annotations

import re
import subprocess
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PREPARE = REPO_ROOT / "scripts" / "review_conflict_prepare.sh"
RESOLVE = REPO_ROOT / "scripts" / "review_conflict_resolve.sh"

MANIFEST_PATH = ".ai/.workspace_source_manifest.txt"
MERGE_RESOLVE_COMMIT_MESSAGE = "[ai-merge-resolve] resolve merge conflicts"


def _prepare_text() -> str:
	return PREPARE.read_text(encoding="utf-8")


def _union_block(text: str) -> str:
	"""The union-merge region: from the path constant to the empty-allowlist check."""
	start = text.index('MANIFEST_UNION_PATH=".ai/.workspace_source_manifest.txt"')
	end = text.index("# When the allowlist is empty there is nothing for Codex to", start)
	return text[start:end]


def test_prepare_names_the_manifest_and_kill_switch() -> None:
	text = _prepare_text()
	assert f'MANIFEST_UNION_PATH="{MANIFEST_PATH}"' in text, (
		"prepare script must pin the manifest path constant"
	)
	block = _union_block(text)
	assert 'CONFLICT_MANIFEST_UNION_ENABLED:-true' in block, (
		"union-merge must be gated on CONFLICT_MANIFEST_UNION_ENABLED with a true default"
	)


def test_prepare_excludes_integration_sync_branches() -> None:
	block = _union_block(_prepare_text())
	assert "orchestrator/project-*)" in block, (
		"union-merge must exclude orchestrator/project-* integration-sync branches: "
		"their fingerprint-violation expansion widens the resolver working set after "
		"this decision point"
	)
	# The exclusion must precede the set-algebra pipeline within the block.
	assert block.index("orchestrator/project-*)") < block.index("comm -12"), (
		"integration-sync exclusion must come before the union-merge pipeline"
	)


def test_prepare_requires_two_sided_content_conflict() -> None:
	block = _union_block(_prepare_text())
	assert "git ls-files -u --" in block and "*' 2 '*' 3 '*" in block, (
		"union-merge must require index stages 2 AND 3 (two-sided content conflict); "
		"delete/modify shapes fall through to the Codex resolver"
	)


def test_prepare_early_commit_branch_contract() -> None:
	block = _union_block(_prepare_text())
	assert f'git commit -m "{MERGE_RESOLVE_COMMIT_MESSAGE}"' in block, (
		"manifest-only resolutions must commit with the exact [ai-merge-resolve] "
		"message downstream tooling matches on"
	)
	assert 'echo "CONFLICT_RESOLVED=true" >> "$GITHUB_ENV"' in block, (
		"manifest-only resolutions must signal CONFLICT_RESOLVED=true so push, "
		"Telegram, and the legacy re-dispatch fire as in the Codex path"
	)
	assert "MERGE_CONFLICT=false" not in block, (
		"the union-merge block must NOT clear MERGE_CONFLICT: the ready-to-merge "
		"gate keys off it to keep resolver commits reviewed before merge"
	)


def test_prepare_uses_c_locale_set_algebra() -> None:
	block = _union_block(_prepare_text())
	for needle in (
		'LC_ALL=C comm -12 "${_mu_dir}/ours" "${_mu_dir}/theirs"',
		'LC_ALL=C comm -13 "${_mu_dir}/base" "${_mu_dir}/ours"',
		'LC_ALL=C comm -13 "${_mu_dir}/base" "${_mu_dir}/theirs"',
	):
		assert needle in block, f"set-algebra line missing or reflowed: {needle}"
	assert "LC_ALL=C sort -u" in block, (
		"stage inputs and the merged output must be LC_ALL=C sorted to match "
		"materialize_source_tree()'s Python str sort"
	)


def test_resolve_short_circuits_before_model_invocation() -> None:
	text = RESOLVE.read_text(encoding="utf-8")
	guard = re.search(
		r'if \[ "\$\{CONFLICT_RESOLVED:-false\}" = "true" \]; then\n[^\n]*\n\s*exit 0',
		text,
	)
	assert guard is not None, (
		"review_conflict_resolve.sh must exit 0 when CONFLICT_RESOLVED=true was "
		"already set by the prepare step"
	)
	first_model_ref = min(
		i for i in (text.find("opencode_helpers.sh"), text.find("OPENCODE_HELPERS_PATH")) if i >= 0
	)
	assert guard.start() < first_model_ref, (
		"the CONFLICT_RESOLVED short-circuit must precede every model-invocation "
		"code path in review_conflict_resolve.sh"
	)


def test_union_merge_pipeline_functional() -> None:
	"""Run the live snippet from the prepare script against a real conflict.

	The snippet between the mktemp line and its cleanup only references
	``MANIFEST_UNION_PATH`` and ``_mu_dir``, so it is runnable verbatim
	inside a scratch repository with an in-progress conflicted merge.
	Testing the extracted live text (not a copy) keeps this green only
	while the shipped pipeline itself is correct.
	"""
	text = _prepare_text()
	block = _union_block(text)
	start = block.index('_mu_dir="$(mktemp -d)"')
	end = block.index('rm -rf "${_mu_dir}"', start) + len('rm -rf "${_mu_dir}"')
	snippet = "\n".join(line.strip() for line in block[start:end].splitlines())

	with tempfile.TemporaryDirectory() as tmp:
		repo = Path(tmp) / "repo"
		repo.mkdir()

		def git(*args: str) -> None:
			subprocess.run(
				["git", *args], cwd=repo, check=True,
				stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
			)

		manifest = repo / MANIFEST_PATH
		git("init", "-q", "-b", "main")
		git("config", "user.name", "t")
		git("config", "user.email", "t@t")
		manifest.parent.mkdir(parents=True)
		manifest.write_text("a.py\nb.py\nm.py\nz.py\n", encoding="utf-8")
		git("add", "-A")
		git("commit", "-qm", "base")
		git("checkout", "-q", "-b", "ours")
		manifest.write_text("a.py\nb.py\nc.py\nm.py\nz.py\n", encoding="utf-8")
		git("commit", "-aqm", "ours adds c.py")
		git("checkout", "-q", "main")
		git("checkout", "-q", "-b", "theirs")
		manifest.write_text("a.py\nb.py\nd.py\nz.py\n", encoding="utf-8")
		git("commit", "-aqm", "theirs adds d.py, removes m.py")
		git("checkout", "-q", "ours")
		merge = subprocess.run(
			["git", "merge", "--no-commit", "--no-ff", "theirs"],
			cwd=repo, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
		)
		assert merge.returncode != 0, "fixture must produce a manifest conflict"

		script = f'set -euo pipefail\nMANIFEST_UNION_PATH="{MANIFEST_PATH}"\n{snippet}\n'
		subprocess.run(["bash", "-c", script], cwd=repo, check=True)

		got = manifest.read_text(encoding="utf-8")
		assert got == "a.py\nb.py\nc.py\nd.py\nz.py\n", (
			f"union-merge must keep both sides' additions and honour theirs-side "
			f"deletion of m.py; got: {got!r}"
		)


def main() -> int:
	test_funcs = [v for k, v in sorted(globals().items()) if k.startswith("test_")]
	passed = 0
	failed = 0
	for func in test_funcs:
		name = func.__name__
		try:
			func()
			print(f"  PASS  {name}")
			passed += 1
		except Exception as e:
			print(f"  FAIL  {name}: {e}")
			failed += 1
	print(f"\n{passed} passed, {failed} failed, {passed + failed} total")
	return 1 if failed > 0 else 0


if __name__ == "__main__":
	raise SystemExit(main())
