#!/usr/bin/env bash
set -euo pipefail

codex_thread_reuse_truthy()
{
	local value="${1:-}"

	case "$(printf '%s' "${value}" | tr '[:upper:]' '[:lower:]')" in
		1|true|yes|on)
			return 0
			;;
		*)
			return 1
			;;
	esac
}

codex_thread_reuse_seed_run_token()
{
	if [ "${CODEX_THREAD_REUSE_RUN_TOKEN_SEEDED:-false}" = 'true' ] && [ -n "${CODEX_THREAD_REUSE_RUN_TOKEN:-}" ]; then
		return 0
	fi

	CODEX_THREAD_REUSE_RUN_TOKEN="$(python3 - <<'PY'
import uuid

print(uuid.uuid4().hex)
PY
)"
	CODEX_THREAD_REUSE_RUN_TOKEN_SEEDED='true'
}

codex_thread_reuse_safe_key()
{
	printf '%s' "${1:-default}" | tr -c 'A-Za-z0-9._-' '_'
}

codex_thread_reuse_runtime_root()
{
	local runtime_dir="${CODEX_THREAD_REUSE_RUNTIME_DIR:-${RUNTIME_DIR:-}}"

	if [ -z "${runtime_dir}" ]; then
		codex_thread_reuse_seed_run_token
		runtime_dir="${TMPDIR:-/tmp}/codex-thread-reuse-run-${CODEX_THREAD_REUSE_RUN_TOKEN:-parent-${PPID:-$$}}"
	fi

	printf '%s/codex-thread-reuse\n' "${runtime_dir}"
}

codex_thread_reuse_ensure_runtime_root()
{
	local root

	root="$(codex_thread_reuse_runtime_root)"
	mkdir -p "${root}/states" "${root}/markers" "${root}/wrapper"
	printf '%s\n' "${root}"
}

codex_thread_reuse_probe_file()
{
	printf '%s/probe.env\n' "$(codex_thread_reuse_ensure_runtime_root)"
}

codex_thread_reuse_state_file()
{
	local state_key="${1:?state key required}"

	printf '%s/states/%s.session_id\n' \
		"$(codex_thread_reuse_ensure_runtime_root)" \
		"$(codex_thread_reuse_safe_key "${state_key}")"
}

codex_thread_reuse_session_id_is_valid()
{
	local session_id="${1:-}"

	[ -n "${session_id}" ] || return 1
	case "${session_id}" in
		*[![:graph:]]*)
			return 1
			;;
	esac

	return 0
}

codex_thread_reuse_clear_session_id()
{
	local state_key="${1:?state key required}"
	local state_file=""

	state_file="$(codex_thread_reuse_state_file "${state_key}")"
	rm -f "${state_file}"
}

codex_thread_reuse_helper_path()
{
	python3 - "${BASH_SOURCE[0]:-$0}" <<'PY'
from pathlib import Path
import sys

print(Path(sys.argv[1]).resolve())
PY
}

codex_thread_reuse_real_codex()
{
	local wrapper_path=""
	local dir=""
	local candidate=""
	local IFS=':'

	if [ -n "${CODEX_THREAD_REUSE_REAL_CODEX:-}" ] && [ -x "${CODEX_THREAD_REUSE_REAL_CODEX}" ]; then
		printf '%s\n' "${CODEX_THREAD_REUSE_REAL_CODEX}"
		return 0
	fi
	# An explicitly selected isolation shim must never fall back to host codex.
	if [ -n "${CODEX_THREAD_REUSE_REAL_CODEX:-}" ]; then
		return 1
	fi

	if [ -n "${CODEX_THREAD_REUSE_WRAPPER_DIR:-}" ]; then
		wrapper_path="${CODEX_THREAD_REUSE_WRAPPER_DIR}/codex"
	fi

	for dir in ${PATH:-}; do
		[ -n "${dir}" ] || dir='.'
		candidate="${dir}/codex"
		if [ -x "${candidate}" ] && [ "${candidate}" != "${wrapper_path}" ]; then
			printf '%s\n' "${candidate}"
			return 0
		fi
	done

	return 1
}

codex_thread_reuse_write_probe_file()
{
	local supported="${1:?supported required}"
	local version="${2:-}"
	local probe_file

	probe_file="$(codex_thread_reuse_probe_file)"
	{
		echo '# Auto-generated by scripts/codex_thread_reuse.sh'
		printf 'supported=%s\n' "${supported}"
		printf 'version=%q\n' "${version}"
	} > "${probe_file}"
}

codex_thread_reuse_probe_supported()
{
	local probe_file=""
	local supported=""
	local version=""
	local real_codex=""
	local resume_help=""
	local rc=0

	probe_file="$(codex_thread_reuse_probe_file)"
	if [ -s "${probe_file}" ]; then
		supported='false'
		# shellcheck disable=SC1090
		source "${probe_file}" || true
		[ "${supported:-false}" = 'true' ]
		return $?
	fi

	if ! real_codex="$(codex_thread_reuse_real_codex)"; then
		codex_thread_reuse_write_probe_file 'false' 'missing-codex'
		return 1
	fi

	version="$("${real_codex}" --version 2>/dev/null | head -n 1 || true)"
	set +e
	resume_help="$("${real_codex}" exec resume --help 2>&1)"
	rc=$?
	set -e
	if [ "${rc}" -eq 0 ] && printf '%s' "${resume_help}" | grep -q 'Usage: codex exec resume'; then
		codex_thread_reuse_write_probe_file 'true' "${version}"
		return 0
	fi

	codex_thread_reuse_write_probe_file 'false' "${version}"
	return 1
}

codex_thread_reuse_begin_capture()
{
	local state_key="${1:?state key required}"
	local markers_dir=""

	markers_dir="$(codex_thread_reuse_ensure_runtime_root)/markers"
	python3 - "${markers_dir}" "$(codex_thread_reuse_safe_key "${state_key}")" <<'PY'
from pathlib import Path
import sys
import time

markers_dir = Path(sys.argv[1])
state_key = sys.argv[2]
markers_dir.mkdir(parents=True, exist_ok=True)
ns = time.time_ns()
path = markers_dir / f"{state_key}.{ns}.marker"
path.write_text(f"{ns}\n", encoding="utf-8")
print(path)
PY
}

codex_thread_reuse_extract_session_id_from_file()
{
	local session_file="${1:?session file required}"

	python3 - "${session_file}" <<'PY'
from __future__ import annotations

import json
import sys
from pathlib import Path

path = Path(sys.argv[1])
try:
	with path.open("r", encoding="utf-8", errors="replace") as handle:
		for raw_line in handle:
			raw_line = raw_line.strip()
			if not raw_line:
				continue
			try:
				payload = json.loads(raw_line)
			except json.JSONDecodeError:
				continue
			if payload.get("type") != "session_meta":
				continue
			session_id = payload.get("payload", {}).get("id", "")
			if isinstance(session_id, str) and session_id:
				print(session_id)
				raise SystemExit(0)
except OSError:
	pass

raise SystemExit(1)
PY
}

codex_thread_reuse_set_session_id()
{
	local state_key="${1:?state key required}"
	local session_id="${2:?session id required}"
	local state_file

	codex_thread_reuse_session_id_is_valid "${session_id}" || return 1
	state_file="$(codex_thread_reuse_state_file "${state_key}")"
	printf '%s\n' "${session_id}" > "${state_file}"
}

codex_thread_reuse_get_session_id()
{
	local state_key="${1:?state key required}"
	local state_file
	local session_id=""

	state_file="$(codex_thread_reuse_state_file "${state_key}")"
	[ -s "${state_file}" ] || return 1
	IFS= read -r session_id < "${state_file}" || true
	codex_thread_reuse_session_id_is_valid "${session_id}" || {
		codex_thread_reuse_clear_session_id "${state_key}"
		return 1
	}
	printf '%s\n' "${session_id}"
}

codex_thread_reuse_record_session_from_marker()
{
	local state_key="${1:?state key required}"
	local marker_file="${2:?marker file required}"
	local session_root="${CODEX_THREAD_REUSE_SESSION_ROOT:-${HOME:-}/.codex/sessions}"
	local session_id=""

	session_id="$(python3 - "${marker_file}" "${session_root}" "${CODEX_THREAD_REUSE_SESSION_CWD:-$(pwd)}" <<'PY'
from __future__ import annotations

import json
import os
import sys
from pathlib import Path

marker_path = Path(sys.argv[1])
session_root = Path(sys.argv[2])
cwd = os.path.realpath(sys.argv[3])

try:
	marker_ns = int(marker_path.read_text(encoding="utf-8").strip())
except (OSError, ValueError):
	raise SystemExit(1)

if not session_root.exists():
	raise SystemExit(1)

candidates: list[tuple[int, str]] = []
for path in session_root.rglob("*.jsonl"):
	try:
		stat = path.stat()
	except OSError:
		continue
	if stat.st_mtime_ns < marker_ns:
		continue
	try:
		with path.open("r", encoding="utf-8", errors="replace") as handle:
			for raw_line in handle:
				raw_line = raw_line.strip()
				if not raw_line:
					continue
				try:
					payload = json.loads(raw_line)
				except json.JSONDecodeError:
					continue
				if payload.get("type") != "session_meta":
					continue
				meta = payload.get("payload", {})
				session_id = meta.get("id", "")
				session_cwd = meta.get("cwd") or ""
				if not isinstance(session_id, str) or not session_id:
					break
				if not isinstance(session_cwd, str) or not session_cwd:
					break
				if os.path.realpath(session_cwd) != cwd:
					break
				candidates.append((stat.st_mtime_ns, session_id))
				break
	except OSError:
		continue

if not candidates:
	raise SystemExit(1)

candidates.sort()
print(candidates[-1][1])
PY
)" || return 1

	codex_thread_reuse_session_id_is_valid "${session_id}" || return 1
	codex_thread_reuse_set_session_id "${state_key}" "${session_id}" || return 1
	printf '%s\n' "${session_id}"
}

codex_thread_reuse_transform_prompt()
{
	local mode="${1:?transform mode required}"
	local source_prompt="${2:?source prompt required}"
	local continuation_prompt="${3:?continuation prompt required}"
	local output_prompt="${4:?output prompt required}"
	local marker_start="${5:-}"
	local marker_end="${6:-}"

	python3 - "${mode}" "${source_prompt}" "${continuation_prompt}" "${output_prompt}" "${marker_start}" "${marker_end}" <<'PY'
from __future__ import annotations

import sys
from pathlib import Path

mode, source_path, continuation_path, output_path, marker_start, marker_end = sys.argv[1:7]


def normalize(path_str: str) -> str:
	text = Path(path_str).read_text(encoding="utf-8")
	text = text.replace("\r\n", "\n").replace("\r", "\n")
	if not text.endswith("\n"):
		text += "\n"
	return text


source_text = normalize(source_path)
continuation_text = normalize(continuation_path)
source_lines = source_text.splitlines(keepends=True)

if mode == "none":
	Path(output_path).write_text(source_text, encoding="utf-8")
	raise SystemExit(0)


def find_marker(marker: str, start_idx: int = 0) -> int:
	for idx in range(start_idx, len(source_lines)):
		if source_lines[idx].rstrip("\n") == marker:
			return idx
	return -1


if mode == "replace-prefix":
	marker_idx = find_marker(marker_start)
	if marker_idx < 0:
		raise SystemExit(1)
	output_text = continuation_text + "".join(source_lines[marker_idx:])
	Path(output_path).write_text(output_text, encoding="utf-8")
	raise SystemExit(0)

if mode == "replace-between":
	start_idx = find_marker(marker_start)
	if start_idx < 0:
		raise SystemExit(1)
	end_idx = find_marker(marker_end, start_idx + 1)
	if end_idx < 0:
		raise SystemExit(1)
	output_text = "".join(source_lines[: start_idx + 1]) + continuation_text + "".join(source_lines[end_idx:])
	Path(output_path).write_text(output_text, encoding="utf-8")
	raise SystemExit(0)

raise SystemExit(2)
PY
}

codex_thread_reuse_resolve_asset()
{
	local repo_path="${1:?repo path required}"
	local candidate=""

	for candidate in \
		"${repo_path}" \
		".codex-workflow-src/${repo_path}" \
		".codex-workflow-src-main/${repo_path}"; do
		if [ -f "${candidate}" ]; then
			printf '%s\n' "${candidate}"
			return 0
		fi
	done

	return 1
}

codex_thread_reuse_install_wrapper()
{
	local state_key="${1:?state key required}"
	local continuation_file="${2:-}"
	local transform_mode="${3:-none}"
	local marker_start="${4:-}"
	local marker_end="${5:-}"
	local root=""
	local wrapper_dir=""
	local helper_path=""
	local real_codex=""

	root="$(codex_thread_reuse_ensure_runtime_root)"
	wrapper_dir="${root}/wrapper/$(codex_thread_reuse_safe_key "${state_key}")"
	helper_path="$(codex_thread_reuse_helper_path)"
	real_codex="$(codex_thread_reuse_real_codex)"

	mkdir -p "${wrapper_dir}"
	cat > "${wrapper_dir}/codex" <<EOF
#!/usr/bin/env bash
set -euo pipefail
exec bash $(printf '%q' "${helper_path}") wrapper-main "\$@"
EOF
	chmod +x "${wrapper_dir}/codex"

	export CODEX_THREAD_REUSE_REAL_CODEX="${real_codex}"
	export CODEX_THREAD_REUSE_HELPER="${helper_path}"
	export CODEX_THREAD_REUSE_WRAPPER_DIR="${wrapper_dir}"
	export CODEX_THREAD_REUSE_STATE_KEY="${state_key}"
	export CODEX_THREAD_REUSE_CONTINUATION_FILE="${continuation_file}"
	export CODEX_THREAD_REUSE_TRANSFORM_MODE="${transform_mode}"
	export CODEX_THREAD_REUSE_MARKER_START="${marker_start}"
	export CODEX_THREAD_REUSE_MARKER_END="${marker_end}"

	printf '%s\n' "${wrapper_dir}"
}

codex_thread_reuse_run_once()
{
	local real_codex="${1:?real codex required}"
	local mode="${2:?mode required}"
	local session_id="${3:-}"
	local prompt_file="${4:?prompt file required}"
	local output_file="${5:?output file required}"
	local phase="${6:?phase required}"
	local model="${7:?model required}"
	local sandbox="${8:-danger-full-access}"
	# Default ON: every workflow runs codex inside the worktree-only
	# workspace (GIT_DIR/GIT_WORK_TREE split, no .git in cwd), where codex
	# aborts with "Not inside a trusted directory and --skip-git-repo-check
	# was not specified". Omitting the flag is a deterministic failure (see
	# #3077, #3194/#3195), so automation callers should leave the check
	# skipped.
	local skip_git_repo_check="${9:-true}"
	local log_file="${10:-}"
	local cumulative_log_file="${11:-}"
	local status_file="${12:-}"
	local stall_guard="${13:-}"
	local heartbeat_helper="${14:-}"
	local timeout_secs="${15:-}"
	local tee_pipe_dir=""
	local tee_pipe=""
	local tee_pid=""
	local stderr_target=""
	local rc=0
	local -a timeout_cmd=()
	local -a runner=()
	local -a cmd=()

	cmd=("${real_codex}" --ask-for-approval never -c model_verbosity=low -c include_apply_patch_tool=true)
	if [ "${mode}" = 'resume' ]; then
		cmd+=(exec resume)
	else
		cmd+=(exec)
	fi
	if codex_thread_reuse_truthy "${skip_git_repo_check}"; then
		cmd+=(--skip-git-repo-check)
	fi
	cmd+=(--model "${model}" --sandbox "${sandbox}")
	if [ "${mode}" = 'resume' ]; then
		cmd+=("${session_id}" -)
	fi

	if [ -n "${timeout_secs}" ]; then
		if command -v timeout >/dev/null 2>&1; then
			timeout_cmd=(timeout --signal=TERM --kill-after=5s "${timeout_secs}s")
		else
			echo "::warning::timeout unavailable; ${phase} will rely on the enclosing job timeout." >&2
		fi
	fi

	if [ -n "${log_file}" ] || [ -n "${cumulative_log_file}" ]; then
		tee_pipe_dir="$(mktemp -d /tmp/codex_thread_reuse_stderr.XXXXXX)"
		tee_pipe="${tee_pipe_dir}/stderr.pipe"
		mkfifo "${tee_pipe}"
		if [ -n "${log_file}" ] && [ -n "${cumulative_log_file}" ]; then
			tee -a "${cumulative_log_file}" "${log_file}" < "${tee_pipe}" >&2 &
		elif [ -n "${log_file}" ]; then
			tee -a "${log_file}" < "${tee_pipe}" >&2 &
		else
			tee -a "${cumulative_log_file}" < "${tee_pipe}" >&2 &
		fi
		tee_pid=$!
		stderr_target="${tee_pipe}"
	fi

	set +e
	if [ -n "${stall_guard}" ] && [ -x "${stall_guard}" ]; then
		runner=()
		runner+=("${stall_guard}" --phase "${phase}" --stdout-file "${output_file}")
		if [ -n "${stderr_target}" ]; then
			runner+=(--stderr-file "${stderr_target}")
		fi
		if [ -n "${status_file}" ]; then
			runner+=(--status-file "${status_file}")
		fi
		runner+=(-- "${cmd[@]}")
		"${timeout_cmd[@]}" "${runner[@]}" < "${prompt_file}"
		rc=$?
	elif [ -n "${heartbeat_helper}" ] && [ -x "${heartbeat_helper}" ]; then
		runner=()
		runner+=("${heartbeat_helper}" --phase "${phase}" --stdout-file "${output_file}")
		if [ -n "${stderr_target}" ]; then
			runner+=(--stderr-file "${stderr_target}")
		fi
		runner+=(-- "${cmd[@]}")
		"${timeout_cmd[@]}" "${runner[@]}" < "${prompt_file}"
		rc=$?
	elif [ -n "${stderr_target}" ]; then
		"${timeout_cmd[@]}" "${cmd[@]}" < "${prompt_file}" > "${output_file}" 2> "${stderr_target}"
		rc=$?
	else
		"${timeout_cmd[@]}" "${cmd[@]}" < "${prompt_file}" > "${output_file}"
		rc=$?
	fi
	set -e

	if [ -n "${tee_pid}" ]; then
		wait "${tee_pid}" 2>/dev/null || true
	fi
	if [ -n "${tee_pipe_dir}" ]; then
		rm -rf "${tee_pipe_dir}"
	fi

	return "${rc}"
}

# Claude engine branch of direct-run (replace-claude-sessions plan Phase 5b).
# Runs the role named by CODEX_THREAD_REUSE_ENGINE_ROLE through claude_run
# (scripts/ai_engine.sh next to this file) in the current directory. One
# Claude session per state key carries the job's retries: the first attempt
# starts it with --session-id, later attempts resume it (claude_run picks
# --resume once the session exists) and, like the codex resume path, get the
# continuation prompt when one is configured. A crashed attempt drops the
# session so the next attempt starts fresh, as a failed codex resume does.
# Returns claude_run's status: 75 means Claude is unavailable and the caller
# runs the codex path instead (plan D1).
codex_thread_reuse_claude_direct_run()
{
	local state_key="${1:?state key required}"
	local prompt_file="${2:?prompt file required}"
	local output_file="${3:?output file required}"
	local log_file="${4:-}"
	local cumulative_log_file="${5:-}"
	local continuation_file="${6:-}"
	local transform_mode="${7:-none}"
	local marker_start="${8:-}"
	local marker_end="${9:-}"
	local timeout_secs="${CODEX_THREAD_REUSE_TIMEOUT_SECS:-}"
	local role="${CODEX_THREAD_REUSE_ENGINE_ROLE:-}"
	local engine_dir=""
	local root=""
	local id_file=""
	local claude_session_id=""
	local effective_prompt="${prompt_file}"
	local claude_prompt=""
	local claude_rc=0
	local -a claude_cmd=()
	local -a tee_targets=()

	engine_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
	if ! [[ "${role}" =~ ^[A-Z][A-Z_]{0,39}$ ]] || [ ! -f "${engine_dir}/ai_engine.sh" ]; then
		echo "AI_ENGINE_FALLBACK role=${role:-unknown} reason=support_missing" >&2
		return 75
	fi
	# shellcheck source=ai_engine.sh
	source "${engine_dir}/ai_engine.sh"

	root="$(codex_thread_reuse_ensure_runtime_root)"
	id_file="${root}/states/claude-$(codex_thread_reuse_safe_key "${state_key}").session"
	claude_session_id="$(cat "${id_file}" 2>/dev/null || true)"
	if ! [[ "${claude_session_id}" =~ ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$ ]]; then
		claude_session_id="$(python3 -c 'import uuid; print(uuid.uuid4())')"
		printf '%s\n' "${claude_session_id}" > "${id_file}"
	fi
	if [ -n "${continuation_file}" ] && compgen -G "${CODEX_THREAD_REUSE_CLAUDE_HOME:-${HOME}}/.claude/projects/*/${claude_session_id}.jsonl" >/dev/null; then
		claude_prompt="$(mktemp /tmp/codex_thread_reuse_claude_prompt.XXXXXX)"
		if codex_thread_reuse_transform_prompt \
			"${transform_mode}" \
			"${prompt_file}" \
			"${continuation_file}" \
			"${claude_prompt}" \
			"${marker_start}" \
			"${marker_end}"; then
			effective_prompt="${claude_prompt}"
		fi
	fi

	[ -n "${log_file}" ] && tee_targets+=("${log_file}")
	[ -n "${cumulative_log_file}" ] && tee_targets+=("${cumulative_log_file}")
	claude_cmd=(bash -c 'source "$1"; shift; claude_run "$@"' _ "${engine_dir}/ai_engine.sh")
	if [ -n "${CODEX_THREAD_REUSE_CLAUDE_RUNNER:-}" ]; then
		if [[ "${CODEX_THREAD_REUSE_CLAUDE_RUNNER}" != /* ]] || [ ! -x "${CODEX_THREAD_REUSE_CLAUDE_RUNNER}" ]; then
			echo "::error::Invalid Claude isolation runner" >&2
			return 1
		fi
		claude_cmd=(bash "${CODEX_THREAD_REUSE_CLAUDE_RUNNER}" claude)
	fi
	if [ -n "${timeout_secs}" ]; then
		if command -v timeout >/dev/null 2>&1; then
			claude_cmd=(timeout --signal=TERM --kill-after=5s "${timeout_secs}s" "${claude_cmd[@]}")
		else
			echo "::warning::timeout unavailable; ${role} will rely on the enclosing job timeout." >&2
		fi
	fi
	if [ "${#tee_targets[@]}" -gt 0 ]; then
		"${claude_cmd[@]}" "${role}" "${effective_prompt}" "${output_file}" "${PWD}" "${claude_session_id}" \
			2> >(tee -a "${tee_targets[@]}" >&2) || claude_rc=$?
	else
		"${claude_cmd[@]}" "${role}" "${effective_prompt}" "${output_file}" "${PWD}" "${claude_session_id}" || claude_rc=$?
	fi
	if [ -n "${claude_prompt}" ]; then
		rm -f "${claude_prompt}"
	fi
	if [ "${claude_rc}" -ne 0 ]; then
		rm -f "${id_file}"
	fi
	return "${claude_rc}"
}

codex_thread_reuse_direct_run()
{
	local state_key="${CODEX_THREAD_REUSE_STATE_KEY:?CODEX_THREAD_REUSE_STATE_KEY is required}"
	local prompt_file="${CODEX_THREAD_REUSE_PROMPT_FILE:?CODEX_THREAD_REUSE_PROMPT_FILE is required}"
	local output_file="${CODEX_THREAD_REUSE_OUTPUT_FILE:?CODEX_THREAD_REUSE_OUTPUT_FILE is required}"
	local phase="${CODEX_THREAD_REUSE_PHASE:?CODEX_THREAD_REUSE_PHASE is required}"
	local model="${CODEX_THREAD_REUSE_MODEL:?CODEX_THREAD_REUSE_MODEL is required}"
	local sandbox="${CODEX_THREAD_REUSE_SANDBOX:-danger-full-access}"
	local log_file="${CODEX_THREAD_REUSE_LOG_FILE:-}"
	local cumulative_log_file="${CODEX_THREAD_REUSE_CUMULATIVE_LOG_FILE:-}"
	local status_file="${CODEX_THREAD_REUSE_STATUS_FILE:-}"
	local stall_guard="${CODEX_THREAD_REUSE_STALL_GUARD_HELPER:-}"
	local heartbeat_helper="${CODEX_THREAD_REUSE_HEARTBEAT_HELPER:-}"
	# Default ON — see the rationale in codex_thread_reuse_run_once.
	# Automation callers should leave codex's git-repo/trust check skipped.
	local skip_git_repo_check="${CODEX_THREAD_REUSE_SKIP_GIT_REPO_CHECK:-true}"
	local timeout_secs="${CODEX_THREAD_REUSE_TIMEOUT_SECS:-}"
	local continuation_file="${CODEX_THREAD_REUSE_CONTINUATION_FILE:-}"
	local transform_mode="${CODEX_THREAD_REUSE_TRANSFORM_MODE:-none}"
	local marker_start="${CODEX_THREAD_REUSE_MARKER_START:-}"
	local marker_end="${CODEX_THREAD_REUSE_MARKER_END:-}"
	local real_codex=""
	local capture_marker=""
	local effective_prompt="${prompt_file}"
	local transformed_prompt=""
	local reuse_available='false'
	local resume_session_id=""
	local resume_allowed='false'
	local rc=0
	local engine_rc=0
	local claude_unavailable_file=""

	# Claude engine (plan Phase 5b): CODEX_THREAD_REUSE_ENGINE=claude runs the
	# role on Claude first; only exit 75 (Claude unavailable) continues to the
	# codex path below, which is unchanged.
	if [ "${CODEX_THREAD_REUSE_ENGINE:-codex}" = 'claude' ]; then
		claude_unavailable_file="$(codex_thread_reuse_ensure_runtime_root)/states/claude-$(codex_thread_reuse_safe_key "${state_key}").unavailable"
		if [ ! -f "${claude_unavailable_file}" ]; then
			AI_ENGINE_MODEL_HINT="${model}" \
				AI_ENGINE_EFFORT_HINT="${AI_ENGINE_EFFORT_HINT:-${MODEL_REASONING_EFFORT:-}}" \
				codex_thread_reuse_claude_direct_run \
				"${state_key}" \
				"${prompt_file}" \
				"${output_file}" \
				"${log_file}" \
				"${cumulative_log_file}" \
				"${continuation_file}" \
				"${transform_mode}" \
				"${marker_start}" \
				"${marker_end}" || engine_rc=$?
			if [ "${engine_rc}" -ne 75 ]; then
				return "${engine_rc}"
			fi
			: > "${claude_unavailable_file}"
		fi
		echo "Claude unavailable for ${state_key}; running the codex path (plan D1)." >&2
	fi

	real_codex="$(codex_thread_reuse_real_codex)"

	if codex_thread_reuse_truthy "${CODEX_THREAD_REUSE_ENABLED:-false}" \
		&& codex_thread_reuse_probe_supported; then
		reuse_available='true'
		resume_session_id="$(codex_thread_reuse_get_session_id "${state_key}" || true)"
	fi

	if [ "${reuse_available}" = 'true' ] \
		&& [ -n "${resume_session_id}" ]; then
		if [ -n "${continuation_file}" ]; then
			transformed_prompt="$(mktemp /tmp/codex_thread_reuse_prompt.XXXXXX)"
			if codex_thread_reuse_transform_prompt \
				"${transform_mode}" \
				"${prompt_file}" \
				"${continuation_file}" \
				"${transformed_prompt}" \
				"${marker_start}" \
				"${marker_end}"; then
				effective_prompt="${transformed_prompt}"
				resume_allowed='true'
			else
				echo "::warning::Thread-reuse prompt transformation failed for ${state_key}; falling back to fresh exec." >&2
			fi
		else
			resume_allowed='true'
		fi
	fi

	if [ "${reuse_available}" = 'true' ]; then
		capture_marker="$(codex_thread_reuse_begin_capture "${state_key}")"
	fi
	if [ "${resume_allowed}" = 'true' ]; then
		if codex_thread_reuse_run_once \
			"${real_codex}" \
			'resume' \
			"${resume_session_id}" \
			"${effective_prompt}" \
			"${output_file}" \
			"${phase}" \
			"${model}" \
			"${sandbox}" \
			"${skip_git_repo_check}" \
			"${log_file}" \
			"${cumulative_log_file}" \
			"${status_file}" \
			"${stall_guard}" \
			"${heartbeat_helper}" \
			"${timeout_secs}"; then
			rc=0
		else
			rc=$?
			echo "::warning::Codex thread reuse failed for ${state_key}; falling back to fresh exec." >&2
			codex_thread_reuse_clear_session_id "${state_key}"
			capture_marker="$(codex_thread_reuse_begin_capture "${state_key}")"
			if codex_thread_reuse_run_once \
				"${real_codex}" \
				'exec' \
				'' \
				"${prompt_file}" \
				"${output_file}" \
				"${phase}" \
				"${model}" \
				"${sandbox}" \
				"${skip_git_repo_check}" \
				"${log_file}" \
				"${cumulative_log_file}" \
				"${status_file}" \
				"${stall_guard}" \
				"${heartbeat_helper}" \
				"${timeout_secs}"; then
				rc=0
			else
				rc=$?
			fi
		fi
	else
		if codex_thread_reuse_run_once \
			"${real_codex}" \
			'exec' \
			'' \
			"${prompt_file}" \
			"${output_file}" \
			"${phase}" \
			"${model}" \
			"${sandbox}" \
			"${skip_git_repo_check}" \
			"${log_file}" \
			"${cumulative_log_file}" \
			"${status_file}" \
			"${stall_guard}" \
			"${heartbeat_helper}" \
			"${timeout_secs}"; then
			rc=0
		else
			rc=$?
		fi
	fi

	if [ "${reuse_available}" = 'true' ] && [ -n "${capture_marker}" ]; then
		codex_thread_reuse_record_session_from_marker "${state_key}" "${capture_marker}" >/dev/null 2>&1 || true
	fi
	if [ -n "${transformed_prompt}" ] && [ -f "${transformed_prompt}" ]; then
		rm -f "${transformed_prompt}"
	fi

	return "${rc}"
}

codex_thread_reuse_wrapper_main()
{
	local real_codex=""
	local state_key="${CODEX_THREAD_REUSE_STATE_KEY:-wrapper}"
	local continuation_file="${CODEX_THREAD_REUSE_CONTINUATION_FILE:-}"
	local transform_mode="${CODEX_THREAD_REUSE_TRANSFORM_MODE:-none}"
	local marker_start="${CODEX_THREAD_REUSE_MARKER_START:-}"
	local marker_end="${CODEX_THREAD_REUSE_MARKER_END:-}"
	local prompt_file=""
	local transformed_prompt=""
	local reuse_available='false'
	local resume_session_id=""
	local capture_marker=""
	local rc=0
	local saw_exec='false'
	local -a prefix=()
	local -a suffix=()

	real_codex="$(codex_thread_reuse_real_codex)"
	while [ "$#" -gt 0 ]; do
		if [ "${saw_exec}" = 'false' ]; then
			if [ "$1" = 'exec' ]; then
				saw_exec='true'
				shift
				continue
			fi
			prefix+=("$1")
			shift
			continue
		fi
		suffix+=("$1")
		shift
	done

	if [ "${saw_exec}" != 'true' ]; then
		exec "${real_codex}" "${prefix[@]}"
	fi
	if [ "${#suffix[@]}" -gt 0 ] && [ "${suffix[0]}" = 'resume' ]; then
		exec "${real_codex}" "${prefix[@]}" exec "${suffix[@]}"
	fi

	prompt_file="$(mktemp /tmp/codex_thread_reuse_wrapper_prompt.XXXXXX)"
	trap 'rm -f "${prompt_file:-}" "${transformed_prompt:-}"' EXIT
	cat > "${prompt_file}"

	if codex_thread_reuse_truthy "${CODEX_THREAD_REUSE_ENABLED:-false}" \
		&& [ -n "${continuation_file}" ] \
		&& codex_thread_reuse_probe_supported; then
		reuse_available='true'
		resume_session_id="$(codex_thread_reuse_get_session_id "${state_key}" || true)"
	fi
	if [ "${reuse_available}" = 'true' ] \
		&& [ -n "${resume_session_id}" ]; then
		transformed_prompt="$(mktemp /tmp/codex_thread_reuse_wrapper_transformed.XXXXXX)"
		if codex_thread_reuse_transform_prompt \
			"${transform_mode}" \
			"${prompt_file}" \
			"${continuation_file}" \
			"${transformed_prompt}" \
			"${marker_start}" \
			"${marker_end}"; then
			capture_marker="$(codex_thread_reuse_begin_capture "${state_key}")"
			set +e
			"${real_codex}" "${prefix[@]}" exec resume "${suffix[@]}" "${resume_session_id}" - < "${transformed_prompt}"
			rc=$?
			set -e
			if [ "${rc}" -eq 0 ]; then
				codex_thread_reuse_record_session_from_marker "${state_key}" "${capture_marker}" >/dev/null 2>&1 || true
				rm -f "${prompt_file}" "${transformed_prompt}"
				exit 0
			fi
			echo "::warning::Codex thread reuse failed for ${state_key}; falling back to fresh exec." >&2
			codex_thread_reuse_clear_session_id "${state_key}"
		else
			echo "::warning::Thread-reuse prompt transformation failed for ${state_key}; falling back to fresh exec." >&2
		fi
	fi

	if [ "${reuse_available}" = 'true' ]; then
		capture_marker="$(codex_thread_reuse_begin_capture "${state_key}")"
	fi
	set +e
	"${real_codex}" "${prefix[@]}" exec "${suffix[@]}" < "${prompt_file}"
	rc=$?
	set -e
	if [ "${reuse_available}" = 'true' ] && [ -n "${capture_marker}" ]; then
		codex_thread_reuse_record_session_from_marker "${state_key}" "${capture_marker}" >/dev/null 2>&1 || true
	fi
	rm -f "${prompt_file}"
	if [ -n "${transformed_prompt}" ] && [ -f "${transformed_prompt}" ]; then
		rm -f "${transformed_prompt}"
	fi
	exit "${rc}"
}

codex_thread_reuse_main()
{
	local cmd="${1:-}"
	shift || true

	case "${cmd}" in
		probe-supported)
			codex_thread_reuse_probe_supported
			;;
		begin-capture)
			codex_thread_reuse_begin_capture "$@"
			;;
		extract-session-id)
			codex_thread_reuse_extract_session_id_from_file "$@"
			;;
		record-session)
			codex_thread_reuse_record_session_from_marker "$@"
			;;
		session-get)
			codex_thread_reuse_get_session_id "$@"
			;;
		transform-prompt)
			codex_thread_reuse_transform_prompt "$@"
			;;
		direct-run)
			codex_thread_reuse_direct_run
			;;
		wrapper-main)
			codex_thread_reuse_wrapper_main "$@"
			;;
		resolve-asset)
			codex_thread_reuse_resolve_asset "$@"
			;;
		''|-h|--help|help)
			cat <<'EOF'
Usage: codex_thread_reuse.sh <command> [args...]

Commands:
  probe-supported
  begin-capture <state-key>
  extract-session-id <session-jsonl>
  record-session <state-key> <marker-file>
  session-get <state-key>
  transform-prompt <mode> <source> <continuation> <output> <marker-start> [marker-end]
  direct-run
  wrapper-main
  resolve-asset <repo-path>
EOF
			;;
		*)
			echo "Unknown command: ${cmd}" >&2
			return 2
			;;
	esac
}

codex_thread_reuse_seed_run_token

if [ "${BASH_SOURCE[0]}" = "$0" ]; then
	codex_thread_reuse_main "$@"
fi
