#!/usr/bin/env bash
set -euo pipefail

PYTHONDONTWRITEBYTECODE=1 python3 - "$@" <<'PY'
from __future__ import annotations

import argparse
import fnmatch
import os
import re
import sys
from functools import lru_cache
from pathlib import Path, PurePosixPath


DEFAULT_SKIP_GLOBS = [
	"package-lock.json",
	"bun.lock",
	"yarn.lock",
	"pnpm-lock.yaml",
	"Cargo.lock",
	"poetry.lock",
	"go.sum",
	"*.min.js",
	"*.min.css",
	"*.map",
	"*.tsbuildinfo",
]
DEFAULT_EXEMPT_GLOBS = "db/contracts/**,**/migrations/**,**/migrate/**"
GENERATED_MARKERS: list[tuple[str, str]] = [
	("@generated", "@generated"),
	("generated file", "GENERATED FILE"),
	("do not edit", "DO NOT EDIT"),
	("eslint-disable", "/* eslint-disable */"),
	("# generated by", "# GENERATED BY"),
]
GENERATED_MARKER_SCAN_BYTES = 4096
GENERATED_MARKER_SCAN_LINES = 5
DIFF_HEADER_RE = re.compile(r"^diff --git a/(.+?) b/(.+)$")
HUNK_HEADER_RE = re.compile(r"^@@ -(?P<old_start>\d+)(?:,\d+)? \+(?P<new_start>\d+)(?:,\d+)? @@")


def parse_csv(value: str) -> list[str]:
	return [item.strip() for item in value.split(",") if item.strip()]


def path_matches(path: str, pattern: str) -> bool:
	pure = PurePosixPath(path)
	if "/" not in pattern:
		return pure.name == pattern or fnmatch.fnmatch(pure.name, pattern) or pure.match(pattern)
	path_parts = pure.parts
	pattern_parts = PurePosixPath(pattern).parts

	@lru_cache(maxsize=None)
	def match_parts(path_idx: int, pattern_idx: int) -> bool:
		while pattern_idx < len(pattern_parts):
			pattern_part = pattern_parts[pattern_idx]
			if pattern_part == "**":
				if pattern_idx + 1 == len(pattern_parts):
					return True
				for next_path_idx in range(path_idx, len(path_parts) + 1):
					if match_parts(next_path_idx, pattern_idx + 1):
						return True
				return False
			if path_idx >= len(path_parts) or not fnmatch.fnmatchcase(path_parts[path_idx], pattern_part):
				return False
			path_idx += 1
			pattern_idx += 1
		return path_idx == len(path_parts)

	return match_parts(0, 0)


def first_matching_glob(path: str, patterns: list[str]) -> str | None:
	for pattern in patterns:
		if path_matches(path, pattern):
			return pattern
	return None


def detect_generated_marker_in_fragments(fragments: list[str]) -> str | None:
	window_parts: list[str] = []
	total = 0
	for index, fragment in enumerate(fragments):
		if index >= GENERATED_MARKER_SCAN_LINES:
			break
		window_parts.append(fragment)
		total += len(fragment)
		if total >= GENERATED_MARKER_SCAN_BYTES:
			break
	window = "".join(window_parts)[:GENERATED_MARKER_SCAN_BYTES].lower()
	for needle, label in GENERATED_MARKERS:
		if needle in window:
			return label
	return None


def detect_generated_marker(repo_root: Path, rel_path: str) -> str | None:
	file_path = repo_root / rel_path
	if not file_path.is_file():
		return None
	try:
		with file_path.open("rb") as handle:
			window = handle.read(GENERATED_MARKER_SCAN_BYTES).decode("utf-8", errors="replace")
	except OSError:
		return None
	return detect_generated_marker_in_fragments(window.splitlines(keepends=True))


def hunk_starts_at_file_top(header: str) -> bool:
	match = HUNK_HEADER_RE.match(header.rstrip("\n"))
	if not match:
		return False
	old_start = int(match.group("old_start"))
	new_start = int(match.group("new_start"))
	return old_start <= 1 and new_start <= 1 and (old_start == 1 or new_start == 1)


def detect_generated_marker_in_block(block: list[str]) -> str | None:
	first_hunk_header = next((line for line in block if line.startswith("@@")), None)
	if not first_hunk_header or not hunk_starts_at_file_top(first_hunk_header):
		return None
	scanned: list[str] = []
	in_first_hunk = False
	for line in block:
		if line.startswith("@@"):
			if in_first_hunk:
				break
			in_first_hunk = True
			continue
		if line.startswith(("diff --git ", "index ", "--- ", "+++ ")):
			continue
		if not in_first_hunk:
			continue
		if not line or line[0] not in {" ", "+", "-"}:
			continue
		scanned.append(line[1:])
		if len(scanned) >= GENERATED_MARKER_SCAN_LINES:
			break
	return detect_generated_marker_in_fragments(scanned)


def split_diff(diff_text: str) -> tuple[list[str], list[list[str]]]:
	prefix: list[str] = []
	blocks: list[list[str]] = []
	current: list[str] | None = None
	for line in diff_text.splitlines(keepends=True):
		if line.startswith("diff --git "):
			if current is not None:
				blocks.append(current)
			current = [line]
		elif current is None:
			prefix.append(line)
		else:
			current.append(line)
	if current is not None:
		blocks.append(current)
	return prefix, blocks


def extract_block_path(block: list[str]) -> str | None:
	for line in block:
		match = DIFF_HEADER_RE.match(line.rstrip("\n"))
		if match:
			return match.group(2)
	for line in block:
		if line.startswith("rename to "):
			return line[len("rename to ") :].strip()
	for line in block:
		if line.startswith("+++ b/"):
			return line[len("+++ b/") :].strip()
	return None


def main() -> int:
	parser = argparse.ArgumentParser(description="Filter low-signal reviewer diff files.")
	parser.add_argument("--diff-file", required=True)
	parser.add_argument("--output-diff", required=True)
	parser.add_argument("--kept-paths-file", required=True)
	parser.add_argument("--skipped-paths-file", required=True)
	parser.add_argument("--repo-root", default=".")
	args = parser.parse_args()

	repo_root = Path(args.repo_root)
	diff_path = Path(args.diff_file)
	output_diff_path = Path(args.output_diff)
	kept_paths_path = Path(args.kept_paths_file)
	skipped_paths_path = Path(args.skipped_paths_file)

	extra_globs = parse_csv(os.getenv("REVIEWER_FILTER_EXTRA_GLOBS", ""))
	exempt_globs = parse_csv(os.getenv("REVIEWER_FILTER_EXEMPT_GLOBS", DEFAULT_EXEMPT_GLOBS))
	skip_globs = DEFAULT_SKIP_GLOBS + extra_globs

	output_diff_path.parent.mkdir(parents=True, exist_ok=True)
	kept_paths_path.parent.mkdir(parents=True, exist_ok=True)
	skipped_paths_path.parent.mkdir(parents=True, exist_ok=True)

	diff_text = diff_path.read_text(encoding="utf-8", errors="replace")
	prefix, blocks = split_diff(diff_text)

	kept_blocks: list[str] = []
	kept_paths: list[str] = []
	seen_kept: set[str] = set()
	skipped_rows: list[tuple[str, str]] = []
	seen_skipped: set[tuple[str, str]] = set()

	for block in blocks:
		path = extract_block_path(block)
		if not path:
			kept_blocks.append("".join(block))
			continue
		if first_matching_glob(path, exempt_globs):
			kept_blocks.append("".join(block))
			if path not in seen_kept:
				seen_kept.add(path)
				kept_paths.append(path)
			continue
		reason: str | None = None
		matched_glob = first_matching_glob(path, skip_globs)
		if matched_glob:
			reason = f"path-glob:{matched_glob}"
		else:
			marker = detect_generated_marker(repo_root, path)
			if not marker and not (repo_root / path).is_file():
				marker = detect_generated_marker_in_block(block)
			if marker:
				reason = f"generated-marker:{marker}"
		if reason:
			row = (path, reason)
			if row not in seen_skipped:
				seen_skipped.add(row)
				skipped_rows.append(row)
			continue
		kept_blocks.append("".join(block))
		if path not in seen_kept:
			seen_kept.add(path)
			kept_paths.append(path)

	if blocks:
		output_diff = "".join(prefix) + "".join(kept_blocks)
	else:
		output_diff = diff_text

	output_diff_path.write_text(output_diff, encoding="utf-8")
	kept_paths_path.write_text("\n".join(kept_paths) + ("\n" if kept_paths else ""), encoding="utf-8")
	skipped_paths_path.write_text(
		"\n".join(f"{path}\t{reason}" for path, reason in skipped_rows) + ("\n" if skipped_rows else ""),
		encoding="utf-8",
	)
	return 0


if __name__ == "__main__":
	raise SystemExit(main())
PY
