#!/usr/bin/env bash
# Auto-generated by coding-workflows — DO NOT EDIT

set -euo pipefail

emit_early_init_failure_result()
{
	local exit_code="$?"

	if [ "${exit_code}" -eq 0 ]; then
		return 0
	fi

	if [ "${RESULT_EMITTED:-0}" = "1" ]; then
		return 0
	fi

	RESULT_EMITTED=1
	printf '%s\n' '{"result":"fail","phase":"preflight","total_tests":1,"passed_tests":0,"failed_tests":1,"failures":[{"test":"validate_driver_init","error":"validate driver failed during early initialization","log_tail":""}],"duration_seconds":0}'
}

trap emit_early_init_failure_result EXIT

ENV_FILE="${VALIDATE_ENV_FILE:-validation/validate.env}"
if [ -f "${ENV_FILE}" ]; then
	set -a
	# shellcheck disable=SC1090
	source "${ENV_FILE}"
	set +a
fi

COMPOSE_FILE="${COMPOSE_FILE:-validation/docker-compose.test.yml}"
APP_SERVICE="${APP_SERVICE:-app}"
APP_URL="${APP_URL:-http://localhost:8080/health}"
HEALTH_TIMEOUT="${HEALTH_TIMEOUT:-120}"
HEALTH_POLL_INTERVAL="${HEALTH_POLL_INTERVAL:-2}"
PHASE="${PHASE:-runtime_validation}"
TEST_DIR="${TEST_DIR:-validation/tests}"
LOG_DIR="${LOG_DIR:-validation/logs}"
COMPOSE_LOG="${COMPOSE_LOG:-${LOG_DIR}/compose.log}"
TAIL_LINES="${TAIL_LINES:-30}"
CANARY_PATTERN="${CANARY_PATTERN:-*canary*.sh}"
CANARY_REQUIRED="${CANARY_REQUIRED:-1}"
# Helper/library scripts live alongside tests but are meant to be sourced,
# not executed as TAP tests. Any basename matching HELPER_PATTERN is excluded
# from test discovery. Default matches the `_lib_*.sh` / `_*.sh` convention.
HELPER_PATTERN="${HELPER_PATTERN:-_*.sh}"

VALIDATION_TEST_USERNAME="${VALIDATION_TEST_USERNAME:-validation-user}"
VALIDATION_TEST_PASSWORD="${VALIDATION_TEST_PASSWORD:-validation-password}"
VALIDATION_TEST_API_KEY="${VALIDATION_TEST_API_KEY:-validation-api-key}"
TEST_USERNAME="${TEST_USERNAME:-${VALIDATION_TEST_USERNAME}}"
TEST_PASSWORD="${TEST_PASSWORD:-${VALIDATION_TEST_PASSWORD}}"
TEST_API_KEY="${TEST_API_KEY:-${VALIDATION_TEST_API_KEY}}"

export VALIDATION_TEST_USERNAME
export VALIDATION_TEST_PASSWORD
export VALIDATION_TEST_API_KEY
export TEST_USERNAME
export TEST_PASSWORD
export TEST_API_KEY

is_positive_int()
{
	local value="$1"
	[[ "${value}" =~ ^[0-9]+$ ]] && [ "${value}" -gt 0 ]
}

if ! is_positive_int "${HEALTH_TIMEOUT}"; then
	HEALTH_TIMEOUT=120
fi

if ! is_positive_int "${HEALTH_POLL_INTERVAL}"; then
	HEALTH_POLL_INTERVAL=2
fi

if ! is_positive_int "${TAIL_LINES}"; then
	TAIL_LINES=30
fi

mkdir -p "${LOG_DIR}"

START_TS="$(date +%s)"
TOTAL_TESTS=0
PASSED_TESTS=0
FAILED_TESTS=0
RESULT="fail"
RESULT_EMITTED=0
TEARDOWN_DONE=0
FINAL_EXIT_CODE=1

FAILURES_FILE="$(mktemp "${TMPDIR:-/tmp}/validate_failures.XXXXXX")"
printf '[]\n' > "${FAILURES_FILE}"

TEST_FILES=()
CANARY_TEST=""

capture_compose_logs()
{
	if [ -f "${COMPOSE_FILE}" ]; then
		mkdir -p "$(dirname -- "${COMPOSE_LOG}")" >/dev/null 2>&1 || true
		docker compose -f "${COMPOSE_FILE}" logs --no-color > "${COMPOSE_LOG}" 2>&1 || true
	fi
}

append_failure()
{
	local test_name="$1"
	local error_message="$2"
	local log_source="${3:-}"
	local log_tail=""

	capture_compose_logs

	if [ -n "${log_source}" ] && [ -f "${log_source}" ]; then
		log_tail="$(tail -n "${TAIL_LINES}" "${log_source}" 2>/dev/null || true)"
	elif [ -f "${COMPOSE_LOG}" ]; then
		log_tail="$(tail -n "${TAIL_LINES}" "${COMPOSE_LOG}" 2>/dev/null || true)"
	fi

	python3 - "${FAILURES_FILE}" "${test_name}" "${error_message}" "${log_tail}" <<'PY'
import json
import sys

failures_path, test_name, error_message, log_tail = sys.argv[1:5]
with open(failures_path, "r", encoding="utf-8") as handle:
    payload = json.load(handle)

payload.append(
    {
        "test": test_name,
        "error": error_message,
        "log_tail": log_tail,
    }
)

with open(failures_path, "w", encoding="utf-8") as handle:
    json.dump(payload, handle)
PY
}

emit_result()
{
	if [ "${RESULT_EMITTED}" = "1" ]; then
		return 0
	fi

	RESULT_EMITTED=1

	local duration
	duration=$(( $(date +%s) - START_TS ))

	RESULT="${RESULT}" \
	PHASE="${PHASE}" \
	TOTAL_TESTS="${TOTAL_TESTS}" \
	PASSED_TESTS="${PASSED_TESTS}" \
	FAILED_TESTS="${FAILED_TESTS}" \
	DURATION="${duration}" \
	FAILURES_FILE_PATH="${FAILURES_FILE}" \
	python3 -c '
import json
import os

failures = []
failures_path = os.environ.get("FAILURES_FILE_PATH")
if failures_path:
    try:
        with open(failures_path, "r", encoding="utf-8") as handle:
            failures = json.load(handle)
    except Exception:
        failures = []

print(
    json.dumps(
        {
            "result": os.environ["RESULT"],
            "phase": os.environ["PHASE"],
            "total_tests": int(os.environ["TOTAL_TESTS"]),
            "passed_tests": int(os.environ["PASSED_TESTS"]),
            "failed_tests": int(os.environ["FAILED_TESTS"]),
            "failures": failures,
            "duration_seconds": int(os.environ["DURATION"]),
        }
    )
)
'
}

teardown()
{
	if [ "${TEARDOWN_DONE}" = "1" ]; then
		return 0
	fi

	TEARDOWN_DONE=1
	capture_compose_logs

	if [ -f "${COMPOSE_FILE}" ]; then
		docker compose -f "${COMPOSE_FILE}" down -v --remove-orphans >/dev/null 2>&1 || true
	fi

	capture_compose_logs
}

mark_unexpected_failure()
{
	local exit_code="$1"

	if [ "${FAILED_TESTS}" -eq 0 ]; then
		TOTAL_TESTS=$((TOTAL_TESTS + 1))
		FAILED_TESTS=$((FAILED_TESTS + 1))
		append_failure "validate.sh:unexpected_error" "validate driver exited unexpectedly (code ${exit_code})" "${COMPOSE_LOG}"
	fi

	RESULT="fail"
	PHASE="runtime_validation"
	FINAL_EXIT_CODE=1
}

finalize()
{
	local exit_code="$?"

	trap - EXIT
	teardown

	if [ "${RESULT_EMITTED}" != "1" ]; then
		if [ "${exit_code}" -ne 0 ]; then
			mark_unexpected_failure "${exit_code}"
		fi
		emit_result
	fi

	rm -f "${FAILURES_FILE}" >/dev/null 2>&1 || true
	exit "${FINAL_EXIT_CODE}"
}

fail_fast()
{
	local test_name="$1"
	local error_message="$2"
	local log_source="${3:-${COMPOSE_LOG}}"
	local fail_phase="${4:-runtime_validation}"

	echo "${error_message}" >&2
	append_failure "${test_name}" "${error_message}" "${log_source}"
	TOTAL_TESTS=$((TOTAL_TESTS + 1))
	FAILED_TESTS=$((FAILED_TESTS + 1))
	RESULT="fail"
	PHASE="${fail_phase}"
	FINAL_EXIT_CODE=1
	emit_result
	exit 1
}

run_preflight_checks()
{
	if ! command -v python3 >/dev/null 2>&1; then
		echo "python3 is required for validation result emission" >&2
		RESULT="fail"
		PHASE="preflight"
		TOTAL_TESTS=1
		PASSED_TESTS=0
		FAILED_TESTS=1
		RESULT_EMITTED=1
		FINAL_EXIT_CODE=1
		printf '%s\n' '{"result":"fail","phase":"preflight","total_tests":1,"passed_tests":0,"failed_tests":1,"failures":[{"test":"preflight_python3","error":"python3 is required for validation result emission","log_tail":""}],"duration_seconds":0}'
		exit 1
	fi

	if ! command -v docker >/dev/null 2>&1; then
		fail_fast "preflight_docker" "docker is not installed" "${COMPOSE_LOG}" "preflight"
	fi

	if ! docker compose version >/dev/null 2>&1; then
		fail_fast "preflight_compose" "docker compose is not available" "${COMPOSE_LOG}" "preflight"
	fi

	if [ ! -f "${COMPOSE_FILE}" ]; then
		fail_fast "preflight_compose_file" "compose file not found: ${COMPOSE_FILE}" "${COMPOSE_LOG}" "preflight"
	fi

	if ! docker compose -f "${COMPOSE_FILE}" config -q >/dev/null 2>&1; then
		fail_fast "preflight_compose_config" "docker compose configuration is invalid" "${COMPOSE_LOG}" "preflight"
	fi

	if [ -n "${APP_URL}" ] && ! command -v curl >/dev/null 2>&1; then
		fail_fast "preflight_curl" "curl is required for APP_URL health checks" "${COMPOSE_LOG}" "preflight"
	fi
}

start_compose()
{
	if ! docker compose -f "${COMPOSE_FILE}" up -d --build >/dev/null 2>&1; then
		capture_compose_logs
		fail_fast "preflight_compose_up" "failed to build/start compose services" "${COMPOSE_LOG}" "startup"
	fi

	capture_compose_logs
}

wait_for_health()
{
	local deadline
	local container_id
	local running
	local health
	local service_ready
	local url_ready

	deadline=$(( $(date +%s) + HEALTH_TIMEOUT ))

	while :; do
		service_ready=0
		url_ready=1

		container_id="$(docker compose -f "${COMPOSE_FILE}" ps -q "${APP_SERVICE}" | head -n1 || true)"
		if [ -n "${container_id}" ]; then
			running="$(docker inspect -f '{{.State.Running}}' "${container_id}" 2>/dev/null || echo false)"
			health="$(docker inspect -f '{{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}' "${container_id}" 2>/dev/null || echo unknown)"
			if [ "${running}" = "true" ] && { [ "${health}" = "healthy" ] || [ "${health}" = "none" ]; }; then
				service_ready=1
			fi
		fi

		if [ -n "${APP_URL}" ]; then
			url_ready=0
			if curl -fsS --max-time 2 "${APP_URL}" >/dev/null 2>&1; then
				url_ready=1
			fi
		fi

		if [ "${service_ready}" -eq 1 ] && [ "${url_ready}" -eq 1 ]; then
			return 0
		fi

		if [ "$(date +%s)" -ge "${deadline}" ]; then
			capture_compose_logs
			fail_fast "startup_health_timeout" "service did not become healthy within HEALTH_TIMEOUT seconds" "${COMPOSE_LOG}" "health"
		fi

		sleep "${HEALTH_POLL_INTERVAL}"
	done
}

discover_tests()
{
	local candidate
	local candidate_name
	local all_candidates=()
	local helper_files=()

	if [ ! -d "${TEST_DIR}" ]; then
		fail_fast "tests_missing" "test directory not found: ${TEST_DIR}" "${COMPOSE_LOG}" "tests"
	fi

	mapfile -t all_candidates < <(find "${TEST_DIR}" -maxdepth 1 -type f -name '*.sh' | sort)

	TEST_FILES=()
	for candidate in "${all_candidates[@]}"; do
		# Use shell parameter expansion instead of `basename` to avoid
		# spawning a subshell for every discovered file.
		candidate_name="${candidate##*/}"
		# Exclude helper/library scripts (e.g. `_lib_*.sh`) from test
		# discovery. They are sourced by real tests and produce no TAP
		# output when executed directly, which would otherwise be
		# misreported as "test produced no TAP output" failures.
		# Guard against an accidentally-empty HELPER_PATTERN so the
		# `[[ ... == ${HELPER_PATTERN} ]]` test never runs with an
		# empty right-hand side (which would degrade to a literal
		# empty-string match).
		if [ -n "${HELPER_PATTERN}" ] && [[ "${candidate_name}" == ${HELPER_PATTERN} ]]; then
			helper_files+=("${candidate}")
			continue
		fi
		TEST_FILES+=("${candidate}")
	done

	if [ "${#helper_files[@]}" -gt 0 ]; then
		{
			echo "validate_driver: excluded ${#helper_files[@]} helper script(s) from test discovery (HELPER_PATTERN='${HELPER_PATTERN}'):"
			printf '  - %s\n' "${helper_files[@]}"
		} >&2
	fi

	if [ "${#TEST_FILES[@]}" -eq 0 ]; then
		fail_fast "tests_missing" "no test scripts found under ${TEST_DIR}" "${COMPOSE_LOG}" "tests"
	fi

	for test_file in "${TEST_FILES[@]}"; do
		if [[ "$(basename "${test_file}")" == ${CANARY_PATTERN} ]]; then
			CANARY_TEST="${test_file}"
			break
		fi
	done

	if [ -z "${CANARY_TEST}" ] && [ "${CANARY_REQUIRED}" != "0" ]; then
		fail_fast "canary_missing" "canary test missing or not executable" "${COMPOSE_LOG}" "tests"
	fi
}

run_single_test()
{
	local test_file="$1"
	local test_type="${2:-test}"
	local test_name
	local test_log
	local exit_code
	local ok_count
	local not_ok_count
	local error_message

	test_name="$(basename "${test_file}")"
	test_log="${LOG_DIR}/${test_name}"

	if [ ! -x "${test_file}" ]; then
		if [ "${test_type}" = "canary" ]; then
			append_failure "${test_name}" "canary test missing or not executable: ${test_file}" "${test_log}"
			TOTAL_TESTS=$((TOTAL_TESTS + 1))
			FAILED_TESTS=$((FAILED_TESTS + 1))
			return 1
		fi
	fi

	set +e
	bash "${test_file}" > "${test_log}" 2>&1
	exit_code=$?
	set -e

	cat "${test_log}"

	ok_count="$(grep -E -c '^[[:space:]]*ok([[:space:]]+[0-9]+)?([[:space:]]|$)' "${test_log}" || true)"
	not_ok_count="$(grep -E -c '^[[:space:]]*not ok([[:space:]]+[0-9]+)?([[:space:]]|$)' "${test_log}" || true)"

	TOTAL_TESTS=$((TOTAL_TESTS + ok_count + not_ok_count))
	PASSED_TESTS=$((PASSED_TESTS + ok_count))
	FAILED_TESTS=$((FAILED_TESTS + not_ok_count))

	if [ "${exit_code}" -eq 0 ] && [ "${ok_count}" -eq 0 ] && [ "${not_ok_count}" -eq 0 ]; then
		TOTAL_TESTS=$((TOTAL_TESTS + 1))
		FAILED_TESTS=$((FAILED_TESTS + 1))
		append_failure "${test_name}" "test produced no TAP output" "${test_log}"
		return 1
	fi

	if [ "${exit_code}" -eq 0 ] && [ "${not_ok_count}" -eq 0 ]; then
		return 0
	fi

	if [ "${not_ok_count}" -eq 0 ]; then
		TOTAL_TESTS=$((TOTAL_TESTS + 1))
		FAILED_TESTS=$((FAILED_TESTS + 1))
	fi

	if [ "${test_type}" = "canary" ]; then
		error_message="canary infrastructure gating failed (exit=${exit_code}, not_ok=${not_ok_count})"
	else
		error_message="test failed (exit=${exit_code}, not_ok=${not_ok_count})"
	fi

	append_failure "${test_name}" "${error_message}" "${test_log}"
	return 1
}

run_tests()
{
	if [ -n "${CANARY_TEST}" ]; then
		if ! run_single_test "${CANARY_TEST}" "canary"; then
			RESULT="fail"
			PHASE="tests"
			FINAL_EXIT_CODE=1
			emit_result
			exit 1
		fi
	fi

	for test_file in "${TEST_FILES[@]}"; do
		if [ "${test_file}" = "${CANARY_TEST}" ]; then
			continue
		fi
		run_single_test "${test_file}" "test" || true
	done
}

trap finalize EXIT

run_preflight_checks
start_compose
wait_for_health
discover_tests
run_tests

if [ "${FAILED_TESTS}" -eq 0 ]; then
	RESULT="pass"
	FINAL_EXIT_CODE=0
else
	RESULT="fail"
	FINAL_EXIT_CODE=1
fi

PHASE="runtime_validation"
emit_result
exit "${FINAL_EXIT_CODE}"
