#!/usr/bin/env bash
# Auto-generated by coding-workflows — DO NOT EDIT

set -euo pipefail

emit_early_init_failure_result()
{
	local exit_code="$?"

	if [ "${exit_code}" -eq 0 ]; then
		return 0
	fi

	if [ "${RESULT_EMITTED:-0}" = "1" ]; then
		return 0
	fi

	RESULT_EMITTED=1
	printf '%s\n' '{"result":"fail","phase":"preflight","total_tests":1,"passed_tests":0,"failed_tests":1,"failures":[{"test":"validate_driver_init","error":"validate driver failed during early initialization","log_tail":""}],"duration_seconds":0}'
}

trap emit_early_init_failure_result EXIT

# Safe parser for the Docker Compose env_file format used by
# `validation/validate.env`. We intentionally do NOT `source` this file
# because the generator prompt (prompts/mode-validate-generate.txt)
# specifies env_file semantics — which permit unquoted values with
# spaces (e.g. `CANARY_TOOLS=curl jq python3 node npm`). Bash `source`
# would parse such a line as the shell simple command
# `CANARY_TOOLS=curl jq python3 node npm` (a one-shot env-prefixed
# invocation of `jq`), which fails preflight with
# `jq: error: python3/0 is not defined` and triggers the
# `validate_driver_init` EXIT trap before any test runs. Parse each
# line ourselves so values with spaces are preserved verbatim.
load_env_file()
{
	local env_path="$1"
	local line key value
	local lineno=0
	while IFS= read -r line || [ -n "${line}" ]; do
		lineno=$((lineno + 1))
		# Strip a trailing CR so CRLF files parse cleanly.
		line="${line%$'\r'}"
		# Strip leading whitespace for the blank/comment check.
		local trimmed="${line#"${line%%[![:space:]]*}"}"
		if [ -z "${trimmed}" ] || [ "${trimmed:0:1}" = "#" ]; then
			continue
		fi
		if [[ ! "${trimmed}" =~ ^([A-Za-z_][A-Za-z0-9_]*)=(.*)$ ]]; then
			# Fail fast — matches the prior `source` under `set -e`
			# behaviour. Silently skipping malformed lines would hide
			# misconfigurations until an unrelated later step reported
			# a missing env var. Print the offending line number and
			# content so the failure is immediately actionable in the
			# validate_driver_init log tail.
			printf 'validate_driver: %s:%s: unparseable env_file line: %s\n' "${env_path}" "${lineno}" "${line}" >&2
			return 1
		fi
		key="${BASH_REMATCH[1]}"
		value="${BASH_REMATCH[2]}"
		# Unwrap a single matched pair of surrounding quotes, matching
		# Docker Compose env_file quoting semantics.
		if [ "${#value}" -ge 2 ]; then
			local first="${value:0:1}"
			local last="${value: -1}"
			if { [ "${first}" = '"' ] && [ "${last}" = '"' ]; } \
				|| { [ "${first}" = "'" ] && [ "${last}" = "'" ]; }; then
				value="${value:1:${#value}-2}"
			fi
		fi
		export "${key}=${value}"
	done < "${env_path}"
}

ENV_FILE="${VALIDATE_ENV_FILE:-validation/validate.env}"
if [ -f "${ENV_FILE}" ]; then
	load_env_file "${ENV_FILE}"
fi

COMPOSE_FILE="${COMPOSE_FILE:-validation/docker-compose.test.yml}"
APP_SERVICE="${APP_SERVICE:-app}"
# Track whether the consumer explicitly configured APP_URL (via environment or
# validation/validate.env) before applying the fallback default. When APP_URL
# is not explicit, wait_for_health skips the host-side HTTP probe and relies
# solely on Docker container state (Running + Health in {healthy,none}). This
# prevents library-type consumers with no real HTTP service from timing out
# on a stale default probe URL while the container is otherwise healthy.
# Use the non-`:-` form so an explicitly empty APP_URL (`APP_URL=`) is
# preserved as the consumer's "disable probe" signal rather than being
# overwritten by the fallback default.
if [ -n "${APP_URL+x}" ]; then
	APP_URL_EXPLICIT=1
else
	APP_URL_EXPLICIT=0
fi
APP_URL="${APP_URL-http://localhost:8080/health}"
# Accept both env var naming conventions. The generate prompt instructs Codex
# to emit HEALTH_TIMEOUT_SECONDS / HEALTH_POLL_INTERVAL_SECONDS in validate.env,
# while the driver historically reads HEALTH_TIMEOUT / HEALTH_POLL_INTERVAL.
# Explicit _SECONDS takes precedence when set; otherwise fall back to the
# legacy name, then the default.
HEALTH_TIMEOUT="${HEALTH_TIMEOUT_SECONDS:-${HEALTH_TIMEOUT:-120}}"
HEALTH_POLL_INTERVAL="${HEALTH_POLL_INTERVAL_SECONDS:-${HEALTH_POLL_INTERVAL:-2}}"
PHASE="${PHASE:-runtime_validation}"
TEST_DIR="${TEST_DIR:-validation/tests}"
LOG_DIR="${LOG_DIR:-validation/logs}"
COMPOSE_LOG="${COMPOSE_LOG:-${LOG_DIR}/compose.log}"
TAIL_LINES="${TAIL_LINES:-30}"
CANARY_PATTERN="${CANARY_PATTERN:-*canary*.sh}"
CANARY_REQUIRED="${CANARY_REQUIRED:-1}"
# Helper/library scripts live alongside tests but are meant to be sourced,
# not executed as TAP tests. Any basename matching HELPER_PATTERN is excluded
# from test discovery. Default matches the `_lib_*.sh` / `_*.sh` convention.
HELPER_PATTERN="${HELPER_PATTERN:-_*.sh}"

VALIDATION_TEST_USERNAME="${VALIDATION_TEST_USERNAME:-validation-user}"
VALIDATION_TEST_PASSWORD="${VALIDATION_TEST_PASSWORD:-validation-password}"
VALIDATION_TEST_API_KEY="${VALIDATION_TEST_API_KEY:-validation-api-key}"
TEST_USERNAME="${TEST_USERNAME:-${VALIDATION_TEST_USERNAME}}"
TEST_PASSWORD="${TEST_PASSWORD:-${VALIDATION_TEST_PASSWORD}}"
TEST_API_KEY="${TEST_API_KEY:-${VALIDATION_TEST_API_KEY}}"

export VALIDATION_TEST_USERNAME
export VALIDATION_TEST_PASSWORD
export VALIDATION_TEST_API_KEY
export TEST_USERNAME
export TEST_PASSWORD
export TEST_API_KEY

is_positive_int()
{
	local value="$1"
	[[ "${value}" =~ ^[0-9]+$ ]] && [ "${value}" -gt 0 ]
}

if ! is_positive_int "${HEALTH_TIMEOUT}"; then
	HEALTH_TIMEOUT=120
fi

if ! is_positive_int "${HEALTH_POLL_INTERVAL}"; then
	HEALTH_POLL_INTERVAL=2
fi

if ! is_positive_int "${TAIL_LINES}"; then
	TAIL_LINES=30
fi

mkdir -p "${LOG_DIR}"

START_TS="$(date +%s)"
TOTAL_TESTS=0
PASSED_TESTS=0
FAILED_TESTS=0
RESULT="fail"
RESULT_EMITTED=0
TEARDOWN_DONE=0
FINAL_EXIT_CODE=1

FAILURES_FILE="$(mktemp "${TMPDIR:-/tmp}/validate_failures.XXXXXX")"
printf '[]\n' > "${FAILURES_FILE}"

if [ -n "${RUNTIME_DIR:-}" ]; then
	VALIDATION_SEMBLE_QUERY_FILE="${VALIDATION_SEMBLE_QUERY_FILE:-${RUNTIME_DIR}/validation_semble_query.json}"
else
	VALIDATION_SEMBLE_QUERY_FILE="${VALIDATION_SEMBLE_QUERY_FILE:-}"
fi

TEST_FILES=()
CANARY_TEST=""

capture_compose_logs()
{
	if [ -f "${COMPOSE_FILE}" ]; then
		mkdir -p "$(dirname -- "${COMPOSE_LOG}")" >/dev/null 2>&1 || true
		local compose_log_tmp
		compose_log_tmp="$(mktemp "${TMPDIR:-/tmp}/compose_capture.XXXXXX" 2>/dev/null || true)"
		if [ -n "${compose_log_tmp}" ]; then
			docker compose -f "${COMPOSE_FILE}" logs --no-color > "${compose_log_tmp}" 2>&1 || true
			if [ -s "${compose_log_tmp}" ]; then
				if ! mv "${compose_log_tmp}" "${COMPOSE_LOG}" 2>/dev/null; then
					cp "${compose_log_tmp}" "${COMPOSE_LOG}" 2>/dev/null || true
				fi
			fi
			rm -f "${compose_log_tmp}" >/dev/null 2>&1 || true
		fi
	fi
}

# Service-aware log capture: writes the specified service's logs to a
# dedicated file so app-specific output is not buried under unrelated
# service chatter (e.g. mongo health probes).
capture_service_logs()
{
	local service="${1:-${APP_SERVICE}}"
	local safe_service="${service//[^A-Za-z0-9_.-]/_}"
	local dest="${LOG_DIR}/${safe_service}.log"
	if [ -f "${COMPOSE_FILE}" ]; then
		mkdir -p "$(dirname -- "${dest}")" >/dev/null 2>&1 || true
		: > "${dest}" 2>/dev/null || true
		local service_log_tmp
		service_log_tmp="$(mktemp "${TMPDIR:-/tmp}/service_capture.XXXXXX" 2>/dev/null || true)"
		if [ -n "${service_log_tmp}" ]; then
			docker compose -f "${COMPOSE_FILE}" logs --no-color -- "${service}" > "${service_log_tmp}" 2>&1 || true
			if [ -s "${service_log_tmp}" ]; then
				if ! mv "${service_log_tmp}" "${dest}" 2>/dev/null; then
					cp "${service_log_tmp}" "${dest}" 2>/dev/null || true
				fi
			fi
			rm -f "${service_log_tmp}" >/dev/null 2>&1 || true
		fi
	fi
}

append_failure()
{
	local test_name="$1"
	local error_message="$2"
	local log_source="${3:-}"
	local skip_capture="${4:-0}"
	local log_tail=""

	if [ "${skip_capture}" != "1" ]; then
		capture_compose_logs
	fi

	if [ -n "${log_source}" ] && [ -f "${log_source}" ]; then
		log_tail="$(tail -n "${TAIL_LINES}" "${log_source}" 2>/dev/null || true)"
	elif [ -f "${COMPOSE_LOG}" ]; then
		log_tail="$(tail -n "${TAIL_LINES}" "${COMPOSE_LOG}" 2>/dev/null || true)"
	fi

	python3 - "${FAILURES_FILE}" "${test_name}" "${error_message}" "${log_tail}" <<'PY'
import json
import sys

failures_path, test_name, error_message, log_tail = sys.argv[1:5]
with open(failures_path, "r", encoding="utf-8") as handle:
    payload = json.load(handle)

payload.append(
    {
        "test": test_name,
        "error": error_message,
        "log_tail": log_tail,
    }
)

with open(failures_path, "w", encoding="utf-8") as handle:
    json.dump(payload, handle)
PY
}

write_semble_query_artifact()
{
	if [ -z "${VALIDATION_SEMBLE_QUERY_FILE:-}" ]; then
		return 0
	fi
	case "${VALIDATION_SEMBLE_QUERY_FILE}" in
		/|/validation_semble_query.json)
			return 0
			;;
	esac

	local query_dir
	query_dir="$(dirname -- "${VALIDATION_SEMBLE_QUERY_FILE}")"
	if [ -z "${query_dir}" ] || [ ! -d "${query_dir}" ]; then
		return 0
	fi

	python3 - "${FAILURES_FILE}" "${VALIDATION_SEMBLE_QUERY_FILE}" <<'PY'
import json
import re
import sys
from pathlib import Path

failures_path, output_path = sys.argv[1:3]

try:
    with open(failures_path, "r", encoding="utf-8") as handle:
        failures = json.load(handle)
except Exception:
    failures = []

if not isinstance(failures, list):
    failures = []

path_re = re.compile(
    r"(?<![A-Za-z0-9_./-])((?:[A-Za-z0-9_.-]+/)*[A-Za-z0-9_.-]+\.(?:py|sh|js|jsx|ts|tsx|json|ya?ml|toml|md|txt))(?:[:(]\d+(?::\d+)?)?"
)
identifier_re = re.compile(r"\b[A-Za-z_][A-Za-z0-9_]{2,}\b")
generic_errors = {
    "exit 1",
    "exit status 1",
    "command failed",
    "validation failed",
    "runtime validation failed",
}
generic_identifier_prefixes = {"test", "assert", "line", "file", "error", "traceback", "validation"}

identifiers = []
evidence = []
seen_identifiers = set()
seen_evidence = set()


def add_identifier(value: str) -> None:
    value = re.sub(r"\s+", " ", value or "").strip()
    if not value:
        return
    lowered = value.lower()
    if lowered in seen_identifiers:
        return
    if lowered in generic_errors:
        return
    if lowered.startswith(("http://", "https://")):
        return
    seen_identifiers.add(lowered)
    identifiers.append(value[:120])


def add_evidence(value: str) -> None:
    value = re.sub(r"\s+", " ", value or "").strip()
    if not value:
        return
    lowered = value.lower()
    if lowered in seen_evidence:
        return
    if lowered in generic_errors:
        return
    seen_evidence.add(lowered)
    evidence.append(value[:220])


for failure in failures[:6]:
    if not isinstance(failure, dict):
        continue
    test_name = str(failure.get("test") or "").strip()
    error_text = str(failure.get("error") or "").strip()
    log_tail = str(failure.get("log_tail") or "")

    if test_name and test_name.lower() not in generic_errors:
        add_identifier(test_name)
    if error_text:
        add_evidence(error_text)

    for blob in (test_name, error_text, log_tail):
        for match in path_re.findall(blob or ""):
            add_identifier(match)

    for token in identifier_re.findall(f"{test_name} {error_text}"):
        lowered = token.lower()
        if lowered in generic_identifier_prefixes:
            continue
        if token.isupper() and len(token) <= 3:
            continue
        if "/" in token:
            continue
        add_identifier(token)

    for line in log_tail.splitlines():
        compact = re.sub(r"\s+", " ", line).strip()
        lowered = compact.lower()
        if not compact:
            continue
        if path_re.search(compact) or any(marker in lowered for marker in (
            "assert",
            "traceback",
            "exception",
            "error:",
            "failed",
            "mismatch",
            "syntaxerror",
            "typeerror",
            "valueerror",
        )):
            add_evidence(compact)
        if len(evidence) >= 6:
            break

query_parts = identifiers[:4] + evidence[:3]
query = " ; ".join(part for part in query_parts if part)
query = re.sub(r"\s+", " ", query).strip()

output = Path(output_path)
if not query or len(query) < 8:
    try:
        output.unlink()
    except OSError:
        pass
    sys.exit(0)

if len(query) > 420:
    query = query[:417].rstrip() + "..."

payload = {
    "query": query,
    "identifiers": identifiers[:8],
    "evidence": evidence[:6],
}
try:
    output.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
except OSError:
    sys.exit(0)
PY
}

emit_result()
{
	if [ "${RESULT_EMITTED}" = "1" ]; then
		return 0
	fi

	RESULT_EMITTED=1
	write_semble_query_artifact || true

	local duration
	duration=$(( $(date +%s) - START_TS ))

	RESULT="${RESULT}" \
	PHASE="${PHASE}" \
	TOTAL_TESTS="${TOTAL_TESTS}" \
	PASSED_TESTS="${PASSED_TESTS}" \
	FAILED_TESTS="${FAILED_TESTS}" \
	DURATION="${duration}" \
	FAILURES_FILE_PATH="${FAILURES_FILE}" \
	python3 -c '
import json
import os

failures = []
failures_path = os.environ.get("FAILURES_FILE_PATH")
if failures_path:
    try:
        with open(failures_path, "r", encoding="utf-8") as handle:
            failures = json.load(handle)
    except Exception:
        failures = []

print(
    json.dumps(
        {
            "result": os.environ["RESULT"],
            "phase": os.environ["PHASE"],
            "total_tests": int(os.environ["TOTAL_TESTS"]),
            "passed_tests": int(os.environ["PASSED_TESTS"]),
            "failed_tests": int(os.environ["FAILED_TESTS"]),
            "failures": failures,
            "duration_seconds": int(os.environ["DURATION"]),
        }
    )
)
'
}

teardown()
{
	local preserve_failure_log=0

	if [ "${TEARDOWN_DONE}" = "1" ]; then
		return 0
	fi

	TEARDOWN_DONE=1
	if [ "${RESULT}" = "fail" ] && { [ "${PHASE}" = "startup" ] || [ "${PHASE}" = "health" ] || [ "${PHASE}" = "dependency_resolution" ]; }; then
		preserve_failure_log=1
	fi

	if [ "${preserve_failure_log}" != "1" ]; then
		# Capture live container logs BEFORE docker compose down. These are the
		# diagnostically valuable logs. Save an immutable pre-down copy so the
		# post-down capture (which may be near-empty) cannot overwrite them.
		capture_compose_logs
		if [ -f "${COMPOSE_LOG}" ]; then
			cp "${COMPOSE_LOG}" "${COMPOSE_LOG%.log}.pre_down.log" 2>/dev/null || true
		fi
	fi

	if [ -f "${COMPOSE_FILE}" ]; then
		docker compose -f "${COMPOSE_FILE}" down -v --remove-orphans >/dev/null 2>&1 || true
	fi

	if [ "${preserve_failure_log}" != "1" ]; then
		# Post-down capture for any final shutdown messages; the primary artifact
		# is the pre_down copy above.
		capture_compose_logs
	fi
}

mark_unexpected_failure()
{
	local exit_code="$1"

	if [ "${FAILED_TESTS}" -eq 0 ]; then
		TOTAL_TESTS=$((TOTAL_TESTS + 1))
		FAILED_TESTS=$((FAILED_TESTS + 1))
		append_failure "validate.sh:unexpected_error" "validate driver exited unexpectedly (code ${exit_code})" "${COMPOSE_LOG}"
	fi

	RESULT="fail"
	PHASE="runtime_validation"
	FINAL_EXIT_CODE=1
}

finalize()
{
	local exit_code="$?"

	trap - EXIT
	teardown

	if [ "${RESULT_EMITTED}" != "1" ]; then
		if [ "${exit_code}" -ne 0 ]; then
			mark_unexpected_failure "${exit_code}"
		fi
		emit_result
	fi

	rm -f "${FAILURES_FILE}" >/dev/null 2>&1 || true
	exit "${FINAL_EXIT_CODE}"
}

fail_fast()
{
	local test_name="$1"
	local error_message="$2"
	local log_source="${3:-${COMPOSE_LOG}}"
	local fail_phase="${4:-runtime_validation}"
	local skip_capture="${5:-0}"

	echo "${error_message}" >&2
	append_failure "${test_name}" "${error_message}" "${log_source}" "${skip_capture}"
	TOTAL_TESTS=$((TOTAL_TESTS + 1))
	FAILED_TESTS=$((FAILED_TESTS + 1))
	RESULT="fail"
	PHASE="${fail_phase}"
	FINAL_EXIT_CODE=1
	emit_result
	exit 1
}

run_preflight_checks()
{
	if ! command -v python3 >/dev/null 2>&1; then
		echo "python3 is required for validation result emission" >&2
		RESULT="fail"
		PHASE="preflight"
		TOTAL_TESTS=1
		PASSED_TESTS=0
		FAILED_TESTS=1
		RESULT_EMITTED=1
		FINAL_EXIT_CODE=1
		printf '%s\n' '{"result":"fail","phase":"preflight","total_tests":1,"passed_tests":0,"failed_tests":1,"failures":[{"test":"preflight_python3","error":"python3 is required for validation result emission","log_tail":""}],"duration_seconds":0}'
		exit 1
	fi

	if ! command -v docker >/dev/null 2>&1; then
		fail_fast "preflight_docker" "docker is not installed" "${COMPOSE_LOG}" "preflight"
	fi

	if ! docker compose version >/dev/null 2>&1; then
		fail_fast "preflight_compose" "docker compose is not available" "${COMPOSE_LOG}" "preflight"
	fi

	if [ ! -f "${COMPOSE_FILE}" ]; then
		fail_fast "preflight_compose_file" "compose file not found: ${COMPOSE_FILE}" "${COMPOSE_LOG}" "preflight"
	fi

	if ! docker compose -f "${COMPOSE_FILE}" config -q >/dev/null 2>&1; then
		fail_fast "preflight_compose_config" "docker compose configuration is invalid" "${COMPOSE_LOG}" "preflight"
	fi

	if [ "${APP_URL_EXPLICIT}" = "1" ] && [ -n "${APP_URL}" ] && ! command -v curl >/dev/null 2>&1; then
		fail_fast "preflight_curl" "curl is required for APP_URL health checks" "${COMPOSE_LOG}" "preflight"
	fi
	# Preflight: scan generated validation Dockerfiles for apt package names that
	# are known to be absent from default Debian/Ubuntu repositories. The canonical
	# case is `mongodb-mongosh`, which is only available via MongoDB's official apt
	# repo (key + source list). Catching this before `docker compose up --build`
	# turns a 20-second opaque `E: Unable to locate package` build failure into a
	# clear, actionable preflight diagnostic. Only trips when the bad package name
	# appears on a non-comment line AND no accompanying MongoDB apt-source hint
	# (`repo.mongodb.org`) is present in the same file.
	for dockerfile in validation/Dockerfile validation/Dockerfile.* validation/*.Dockerfile; do
		[ -f "${dockerfile}" ] || continue
		if grep -Evi '^[[:space:]]*#' "${dockerfile}" \
		   | sed -E 's/[[:space:]]+#.*$//' \
		   | sed -E ':a;N;$!ba;s/\\[[:space:]]*\n[[:space:]]*/ /g' \
		   | grep -Eq 'apt(-get)?[[:space:]].*install.*(^|[^[:alnum:]_-])(mongodb-)?mongosh(=[^[:space:]\\]+)?($|[^[:alnum:]_-])' \
		   && ! grep -Evi '^[[:space:]]*#' "${dockerfile}" \
		   | sed -E 's/[[:space:]]+#.*$//' \
		   | grep -qi 'repo\.mongodb\.org'; then
			fail_fast "preflight_bad_apt_package" "${dockerfile} references 'mongosh'/'mongodb-mongosh' but does not add MongoDB's official apt repo (no 'repo.mongodb.org' reference). mongosh is NOT in Debian/Ubuntu default repos and will fail the compose build with 'E: Unable to locate package mongosh' or 'E: Unable to locate package mongodb-mongosh'. Prefer pymongo, or add the MongoDB apt source + GPG key to the Dockerfile. See mode-validate-generate.txt: 'installing mongosh in validation/Dockerfile.app'." "${COMPOSE_LOG}" "preflight"
		fi
	done
}

# Detect npm ERESOLVE signatures in a build log. Returns 0 if any of the
# recognised npm dependency-resolution error markers are present, 1 otherwise.
# Kept intentionally broad — npm's wording varies across major versions
# ("npm ERR!" vs. "npm error", with or without a "code ERESOLVE" prefix).
detect_eresolve()
{
	local log_file="$1"
	[ -f "${log_file}" ] || return 1
	if grep -Eaiq 'npm.*(ERR!|error).*ERESOLVE' "${log_file}" \
		|| grep -Eaiq 'npm.*(ERR!|error).*Could not resolve dependency' "${log_file}" \
		|| grep -Eaiq 'npm.*(ERR!|error).*Conflicting peer dependency' "${log_file}"; then
		return 0
	fi
	return 1
}

# Emit a concise one-line diagnostic describing the ERESOLVE conflict found
# in the given log, including the conflicting package/version pairs and the
# filesystem paths of the npm artifacts (eresolve-report.txt / debug log)
# so diagnosis is deterministic without having to scrape log_tail.
describe_eresolve()
{
	local log_file="$1"
	if [ ! -f "${log_file}" ]; then
		printf 'npm ERESOLVE dependency conflict (no build log available)\n'
		return 0
	fi
	python3 - "${log_file}" <<'PY'
import re
import sys

path = sys.argv[1]
try:
    with open(path, "rb") as fh:
        fh.seek(0, 2)
        size = fh.tell()
        tail_bytes = 1024 * 1024
        if size > tail_bytes:
            fh.seek(-tail_bytes, 2)
        else:
            fh.seek(0)
        text = fh.read().decode("utf-8", errors="replace")
except OSError:
    print("npm ERESOLVE dependency conflict (build log unreadable)")
    sys.exit(0)

def first(pattern):
    m = re.search(pattern, text)
    return m.group(1).strip() if m else ""

resolving   = first(r'npm (?:ERR!|error)\s+While resolving:\s*(.+)')
found       = first(r'npm (?:ERR!|error)\s+Found:\s*(.+)')
conflicting = first(r'npm (?:ERR!|error)\s+Conflicting peer dependency:\s*(.+)')

artifacts = sorted({
    m for m in re.findall(
        r'[^ \n]*\.npm/_logs/[^ \n]+-(?:eresolve-report\.txt|debug-\d+\.log)',
        text,
    )
})

parts = []
if resolving:
    parts.append(f"while resolving {resolving}")
if found:
    parts.append(f"found {found}")
if conflicting:
    parts.append(f"conflicting peer {conflicting}")

msg = "npm ERESOLVE dependency conflict"
if parts:
    msg += ": " + "; ".join(parts)
if artifacts:
    msg += " (see " + ", ".join(artifacts) + ")"
print(msg)
PY
}

start_compose()
{
	# Dependency precheck: run `docker compose build` as an explicit step
	# before `up -d`. Splitting build from up lets us bucket dependency-
	# resolution failures (e.g. npm ERESOLVE during `RUN npm ci`) as a
	# dedicated `phase=dependency_resolution` harness failure instead of
	# conflating them with generic application startup defects, and keeps
	# runtime/startup assertions gated on a successful image build.
	local build_log
	build_log="$(mktemp "${TMPDIR:-/tmp}/compose_build.XXXXXX")" || fail_fast "preflight_compose_up" "failed to create temp file for compose build output" "${COMPOSE_LOG}" "startup"
	if ! docker compose -f "${COMPOSE_FILE}" build >"${build_log}" 2>&1; then
		# Prepend the build output so the log_tail contains the actual
		# build error (ERESOLVE, buildx permission denied, missing COPY
		# source, etc.) that docker emitted.
		if [ -s "${build_log}" ]; then
			local merged_log
			merged_log="$(mktemp "${TMPDIR:-/tmp}/compose_merged.XXXXXX")" || fail_fast "preflight_compose_up" "failed to create temp file for compose merged output" "${build_log}" "startup" 1
			{
				echo "=== docker compose build output ==="
				cat "${build_log}"
			} > "${merged_log}"
			mkdir -p "$(dirname -- "${COMPOSE_LOG}")" >/dev/null 2>&1 || true
			if ! mv "${merged_log}" "${COMPOSE_LOG}" 2>/dev/null; then
				cp "${merged_log}" "${COMPOSE_LOG}" 2>/dev/null || true
				rm -f "${merged_log}" >/dev/null 2>&1 || true
			fi
		fi

		if detect_eresolve "${build_log}"; then
			local eresolve_msg
			eresolve_msg="$(describe_eresolve "${build_log}" 2>/dev/null || true)"
			[ -n "${eresolve_msg}" ] || eresolve_msg="npm ERESOLVE dependency conflict during image build"
			rm -f "${build_log}" >/dev/null 2>&1 || true
			fail_fast "preflight_dependency_resolution" "${eresolve_msg}" "${COMPOSE_LOG}" "dependency_resolution" 1
		fi

		rm -f "${build_log}" >/dev/null 2>&1 || true
		fail_fast "preflight_compose_up" "failed to build compose services" "${COMPOSE_LOG}" "startup" 1
	fi
	rm -f "${build_log}" >/dev/null 2>&1 || true

	local up_log
	up_log="$(mktemp "${TMPDIR:-/tmp}/compose_up.XXXXXX")" || fail_fast "preflight_compose_up" "failed to create temp file for compose up output" "${COMPOSE_LOG}" "startup"
	if ! docker compose -f "${COMPOSE_FILE}" up -d >"${up_log}" 2>&1; then
		capture_compose_logs
		if [ -s "${up_log}" ]; then
			local merged_log
			merged_log="$(mktemp "${TMPDIR:-/tmp}/compose_merged.XXXXXX")" || fail_fast "preflight_compose_up" "failed to create temp file for compose merged output" "${up_log}" "startup" 1
			{
				echo "=== docker compose up -d output ==="
				cat "${up_log}"
				echo ""
				if [ -f "${COMPOSE_LOG}" ]; then
					echo "=== container logs ==="
					cat "${COMPOSE_LOG}"
				fi
			} > "${merged_log}"
			mkdir -p "$(dirname -- "${COMPOSE_LOG}")" >/dev/null 2>&1 || true
			if ! mv "${merged_log}" "${COMPOSE_LOG}" 2>/dev/null; then
				cp "${merged_log}" "${COMPOSE_LOG}" 2>/dev/null || true
				rm -f "${merged_log}" >/dev/null 2>&1 || true
			fi
		fi
		rm -f "${up_log}" >/dev/null 2>&1 || true
		fail_fast "preflight_compose_up" "failed to start compose services" "${COMPOSE_LOG}" "startup" 1
	fi
	rm -f "${up_log}" >/dev/null 2>&1 || true

	capture_compose_logs
}

wait_for_health()
{
	local deadline
	local container_id
	local running
	local health
	local status
	local exit_code
	local restart_count
	local app_log_tail
	local app_service_log
	local service_ready
	local url_ready

	app_service_log="${LOG_DIR}/${APP_SERVICE//[^A-Za-z0-9_.-]/_}.log"
	deadline=$(( $(date +%s) + HEALTH_TIMEOUT ))

	while :; do
		service_ready=0
		url_ready=1

		container_id="$(docker compose -f "${COMPOSE_FILE}" ps -q --all -- "${APP_SERVICE}" 2>/dev/null | head -n1 || true)"
		if [ -z "${container_id}" ]; then
			container_id="$(docker compose -f "${COMPOSE_FILE}" ps -q -- "${APP_SERVICE}" 2>/dev/null | head -n1 || true)"
		fi
		if [ -n "${container_id}" ]; then
			running="$(docker inspect -f '{{.State.Running}}' "${container_id}" 2>/dev/null || echo false)"
			health="$(docker inspect -f '{{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}' "${container_id}" 2>/dev/null || echo unknown)"
			status="$(docker inspect -f '{{.State.Status}}' "${container_id}" 2>/dev/null || echo unknown)"

			# Fail fast: detect exited or restarting container immediately
			# instead of waiting the full timeout.
			if [ "${status}" = "exited" ] || [ "${status}" = "dead" ]; then
				exit_code="$(docker inspect -f '{{.State.ExitCode}}' "${container_id}" 2>/dev/null || echo unknown)"
				capture_compose_logs
				capture_service_logs "${APP_SERVICE}"
				fail_fast "startup_container_exited" \
					"${APP_SERVICE} container exited (status=${status} exit_code=${exit_code}); check app logs" \
					"${app_service_log}" "health"
			fi
			if [ "${status}" = "restarting" ]; then
				restart_count="$(docker inspect -f '{{.RestartCount}}' "${container_id}" 2>/dev/null || echo unknown)"
				if [[ "${restart_count}" =~ ^[0-9]+$ ]] && [ "${restart_count}" -ge 3 ]; then
					exit_code="$(docker inspect -f '{{.State.ExitCode}}' "${container_id}" 2>/dev/null || echo unknown)"
					capture_compose_logs
					capture_service_logs "${APP_SERVICE}"
					fail_fast "startup_container_restart_loop" \
						"${APP_SERVICE} container in restart loop (restarts=${restart_count} exit_code=${exit_code}); check app logs" \
						"${app_service_log}" "health"
				fi
			fi

			if [ "${running}" = "true" ] && { [ "${health}" = "healthy" ] || [ "${health}" = "none" ]; }; then
				service_ready=1
			fi
		fi

		if [ "${APP_URL_EXPLICIT}" = "1" ] && [ -n "${APP_URL}" ]; then
			url_ready=0
			if curl -fsS --max-time 2 "${APP_URL}" >/dev/null 2>&1; then
				url_ready=1
			fi
		fi

		if [ "${service_ready}" -eq 1 ] && [ "${url_ready}" -eq 1 ]; then
			return 0
		fi

		if [ "$(date +%s)" -ge "${deadline}" ]; then
			# App-focused timeout diagnostics: capture service-specific logs
			# and container state before the combined compose log capture so
			# downstream log tails are actionable.
			capture_service_logs "${APP_SERVICE}"
			app_log_tail="$(tail -n "${TAIL_LINES}" "${app_service_log}" 2>/dev/null || echo "(no service log)")"
			{
				echo "=== ${APP_SERVICE} timeout diagnostics ==="
				# Write app log tail first so the final tailed failure payload
				# still retains infra diagnostics at the end.
				echo "--- ${APP_SERVICE} log tail ---"
				echo "${app_log_tail}"
				echo "--- docker compose ps ---"
				docker compose -f "${COMPOSE_FILE}" ps 2>&1 || true
				if [ -n "${container_id}" ]; then
					echo "--- docker inspect state (${APP_SERVICE}) ---"
					docker inspect -f 'Status={{.State.Status}} Running={{.State.Running}} ExitCode={{.State.ExitCode}} OOMKilled={{.State.OOMKilled}} RestartCount={{.RestartCount}} Health={{if .State.Health}}{{.State.Health.Status}}{{else}}none{{end}}' \
						"${container_id}" 2>&1 || true
					echo "--- docker inspect health log (${APP_SERVICE}) ---"
					docker inspect -f '{{if .State.Health}}{{range .State.Health.Log}}exit={{.ExitCode}} start={{.Start}} output={{.Output}}{{"\n"}}{{end}}{{else}}no healthcheck configured{{end}}' \
						"${container_id}" 2>&1 | tail -n 5 || true
				fi
				echo "=== end diagnostics ==="
			} >> "${app_service_log}" 2>&1 || true
			capture_compose_logs
			fail_fast "startup_health_timeout" \
				"${APP_SERVICE} did not become healthy within ${HEALTH_TIMEOUT}s (last status=${status:-unknown} running=${running:-unknown} health=${health:-unknown})" \
				"${app_service_log}" "health"
		fi

		sleep "${HEALTH_POLL_INTERVAL}"
	done
}

discover_tests()
{
	local candidate
	local candidate_name
	local all_candidates=()
	local helper_files=()

	if [ ! -d "${TEST_DIR}" ]; then
		fail_fast "tests_missing" "test directory not found: ${TEST_DIR}" "${COMPOSE_LOG}" "tests"
	fi

	mapfile -t all_candidates < <(find "${TEST_DIR}" -maxdepth 1 -type f -name '*.sh' | sort)

	TEST_FILES=()
	for candidate in "${all_candidates[@]}"; do
		# Use shell parameter expansion instead of `basename` to avoid
		# spawning a subshell for every discovered file.
		candidate_name="${candidate##*/}"
		# Exclude helper/library scripts (e.g. `_lib_*.sh`) from test
		# discovery. They are sourced by real tests and produce no TAP
		# output when executed directly, which would otherwise be
		# misreported as "test produced no TAP output" failures.
		# Guard against an accidentally-empty HELPER_PATTERN so the
		# `[[ ... == ${HELPER_PATTERN} ]]` test never runs with an
		# empty right-hand side (which would degrade to a literal
		# empty-string match).
		if [ -n "${HELPER_PATTERN}" ] && [[ "${candidate_name}" == ${HELPER_PATTERN} ]]; then
			helper_files+=("${candidate}")
			continue
		fi
		TEST_FILES+=("${candidate}")
	done

	if [ "${#helper_files[@]}" -gt 0 ]; then
		{
			echo "validate_driver: excluded ${#helper_files[@]} helper script(s) from test discovery (HELPER_PATTERN='${HELPER_PATTERN}'):"
			printf '  - %s\n' "${helper_files[@]}"
		} >&2
	fi

	if [ "${#TEST_FILES[@]}" -eq 0 ]; then
		fail_fast "tests_missing" "no test scripts found under ${TEST_DIR}" "${COMPOSE_LOG}" "tests"
	fi

	for test_file in "${TEST_FILES[@]}"; do
		if [[ "$(basename "${test_file}")" == ${CANARY_PATTERN} ]]; then
			CANARY_TEST="${test_file}"
			break
		fi
	done

	if [ -z "${CANARY_TEST}" ] && [ "${CANARY_REQUIRED}" != "0" ]; then
		fail_fast "canary_missing" "canary test missing or not executable" "${COMPOSE_LOG}" "tests"
	fi
}

run_single_test()
{
	local test_file="$1"
	local test_type="${2:-test}"
	local test_name
	local test_log
	local exit_code
	local ok_count
	local not_ok_count
	local error_message

	test_name="$(basename "${test_file}")"
	test_log="${LOG_DIR}/${test_name}"

	if [ ! -x "${test_file}" ]; then
		if [ "${test_type}" = "canary" ]; then
			append_failure "${test_name}" "canary test missing or not executable: ${test_file}" "${test_log}"
			TOTAL_TESTS=$((TOTAL_TESTS + 1))
			FAILED_TESTS=$((FAILED_TESTS + 1))
			return 1
		fi
	fi

	set +e
	bash "${test_file}" > "${test_log}" 2>&1
	exit_code=$?
	set -e

	cat "${test_log}"

	ok_count="$(grep -E -c '^[[:space:]]*ok([[:space:]]+[0-9]+)?([[:space:]]|$)' "${test_log}" || true)"
	not_ok_count="$(grep -E -c '^[[:space:]]*not ok([[:space:]]+[0-9]+)?([[:space:]]|$)' "${test_log}" || true)"

	TOTAL_TESTS=$((TOTAL_TESTS + ok_count + not_ok_count))
	PASSED_TESTS=$((PASSED_TESTS + ok_count))
	FAILED_TESTS=$((FAILED_TESTS + not_ok_count))

	if [ "${exit_code}" -eq 0 ] && [ "${ok_count}" -eq 0 ] && [ "${not_ok_count}" -eq 0 ]; then
		TOTAL_TESTS=$((TOTAL_TESTS + 1))
		FAILED_TESTS=$((FAILED_TESTS + 1))
		append_failure "${test_name}" "test produced no TAP output" "${test_log}"
		return 1
	fi

	if [ "${exit_code}" -eq 0 ] && [ "${not_ok_count}" -eq 0 ]; then
		return 0
	fi

	if [ "${not_ok_count}" -eq 0 ]; then
		TOTAL_TESTS=$((TOTAL_TESTS + 1))
		FAILED_TESTS=$((FAILED_TESTS + 1))
	fi

	if [ "${test_type}" = "canary" ]; then
		error_message="canary infrastructure gating failed (exit=${exit_code}, not_ok=${not_ok_count})"
	else
		error_message="test failed (exit=${exit_code}, not_ok=${not_ok_count})"
	fi

	append_failure "${test_name}" "${error_message}" "${test_log}"
	return 1
}

run_tests()
{
	if [ -n "${CANARY_TEST}" ]; then
		if ! run_single_test "${CANARY_TEST}" "canary"; then
			RESULT="fail"
			PHASE="tests"
			FINAL_EXIT_CODE=1
			emit_result
			exit 1
		fi
	fi

	for test_file in "${TEST_FILES[@]}"; do
		if [ "${test_file}" = "${CANARY_TEST}" ]; then
			continue
		fi
		run_single_test "${test_file}" "test" || true
	done
}

trap finalize EXIT

run_preflight_checks
start_compose
wait_for_health
discover_tests
run_tests

if [ "${FAILED_TESTS}" -eq 0 ]; then
	RESULT="pass"
	FINAL_EXIT_CODE=0
else
	RESULT="fail"
	FINAL_EXIT_CODE=1
fi

PHASE="runtime_validation"
emit_result
exit "${FINAL_EXIT_CODE}"
