name: "Internal: Issue-PR Status Sync"

on:
  pull_request:
    types: [closed]

permissions:
  issues: write

jobs:
  sync-status:
    uses: shubhodeep1/coding-workflows/.github/workflows/issue_pr_status.yml@main
    secrets: inherit
